In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
import plotly.express as px
import os

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
#Indicate columns and target
columns = [
    "id","Airline","Delay","Flight","AirportFrom","AirportTo","DayOfWeek","Length"
]

target = ["Delay"]

In [6]:
file_path = Path("new_airlines")
airlines_df = pd.read_csv(file_path)
airlines_df

            id Airline  Flight AirportFrom AirportTo  DayOfWeek  Length  Delay
0            1      CO     269         SFO       IAH  Wednesday     205      1
1            2      US    1558         PHX       CLT  Wednesday     222      1
2            3      AA    2400         LAX       DFW  Wednesday     165      1
3            4      AA    2466         SFO       DFW  Wednesday     195      1
4            5      AS     108         ANC       SEA  Wednesday     202      0
...        ...     ...     ...         ...       ...        ...     ...    ...
539378  539379      CO     178         OGG       SNA     Friday     326      0
539379  539380      FL     398         SEA       ATL     Friday     305      0
539380  539381      FL     609         SFO       MKE     Friday     255      0
539381  539382      UA      78         HNL       SFO     Friday     313      1
539382  539383      US    1442         LAX       PHL     Friday     301      1

[539383 rows x 8 columns]

In [7]:
#Read data into pandas
#data = pd.read_csv("Airlines.csv")

airlines_df = airlines_df.loc[:, columns].copy()
airlines_df

            id Airline  Delay  Flight AirportFrom AirportTo  DayOfWeek  Length
0            1      CO      1     269         SFO       IAH  Wednesday     205
1            2      US      1    1558         PHX       CLT  Wednesday     222
2            3      AA      1    2400         LAX       DFW  Wednesday     165
3            4      AA      1    2466         SFO       DFW  Wednesday     195
4            5      AS      0     108         ANC       SEA  Wednesday     202
...        ...     ...    ...     ...         ...       ...        ...     ...
539378  539379      CO      0     178         OGG       SNA     Friday     326
539379  539380      FL      0     398         SEA       ATL     Friday     305
539380  539381      FL      0     609         SFO       MKE     Friday     255
539381  539382      UA      1      78         HNL       SFO     Friday     313
539382  539383      US      1    1442         LAX       PHL     Friday     301

[539383 rows x 8 columns]

In [8]:
#Drop the null columns where all values are null
airlines_df = airlines_df.dropna(axis='columns', how='all')

# Drop the null rows
airlines_df = airlines_df.dropna()
airlines_df

            id Airline  Delay  Flight AirportFrom AirportTo  DayOfWeek  Length
0            1      CO      1     269         SFO       IAH  Wednesday     205
1            2      US      1    1558         PHX       CLT  Wednesday     222
2            3      AA      1    2400         LAX       DFW  Wednesday     165
3            4      AA      1    2466         SFO       DFW  Wednesday     195
4            5      AS      0     108         ANC       SEA  Wednesday     202
...        ...     ...    ...     ...         ...       ...        ...     ...
539378  539379      CO      0     178         OGG       SNA     Friday     326
539379  539380      FL      0     398         SEA       ATL     Friday     305
539380  539381      FL      0     609         SFO       MKE     Friday     255
539381  539382      UA      1      78         HNL       SFO     Friday     313
539382  539383      US      1    1442         LAX       PHL     Friday     301

[539383 rows x 8 columns]

In [9]:
#Remove info that does not tell us anything about delay or no delay 
#Flight numbers cannot be used as unique identifier b/c some flights have same flight number but
#are based out of different airports
airlines_df = airlines_df.drop(columns =['id','Flight'],axis=1)
airlines_df

       Airline  Delay AirportFrom AirportTo  DayOfWeek  Length
0           CO      1         SFO       IAH  Wednesday     205
1           US      1         PHX       CLT  Wednesday     222
2           AA      1         LAX       DFW  Wednesday     165
3           AA      1         SFO       DFW  Wednesday     195
4           AS      0         ANC       SEA  Wednesday     202
...        ...    ...         ...       ...        ...     ...
539378      CO      0         OGG       SNA     Friday     326
539379      FL      0         SEA       ATL     Friday     305
539380      FL      0         SFO       MKE     Friday     255
539381      UA      1         HNL       SFO     Friday     313
539382      US      1         LAX       PHL     Friday     301

[539383 rows x 6 columns]

# Initial Visulizations/Counts Using Plotly - ran as separate file see (initial_comparison)

In [10]:
import pandas as pd
from path import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [11]:
#Create plot grouped by airline to count 
#df = airlines_df[['Airline','Delay']].groupby('Airline').agg('count').reset_index()
#fig = px.bar(airlines_df, x='Airline', y='Delay')
#fig.show()

In [12]:
#Create plot grouped by DayOfWeek to count 
#df = airlines_df[['DayOfWeek','Delay']].groupby('Airline').agg('count').reset_index()
#fig = px.bar(airlines_df, x='DayOfWeek', y='Delay')
#fig.show()

In [13]:

#Create plot grouped by departing airport to count 
#airlines_df = airlines_df[['AirportFrom','Delay']].groupby('AirportFrom').agg('count').reset_index()
#fig = px.bar(airlines_df, x='AirportFrom', y='Delay')
#fig.show()

In [14]:
#Create plot grouped by departing airport to count 
#airlines_df = airlines_df[['AirportTo','Delay']].groupby('AirportTo').agg('count').reset_index()
#fig = px.bar(airlines_df, x='AirportTo', y='Delay')
#fig.show()

In [15]:
#Create plot grouped by departing airport to count 
#airlines_df = data[['Length','Delay']].groupby('Length').agg('count').reset_index()
#fig = px.bar(airlines_df, x='Length', y='Delay')
#fig.show()

# Data Preparation

In [16]:
#Change numbers to day of week to later be converted to 1s and 0s - removed from code because already incorporated in updated CSV
#days = {1:'Monday', 2:'Tuesday', 3:'Wednesday', 4:'Thursday', 5:'Friday', 6:'Saturday', 7:'Sunday'}

In [17]:
#airlines_df['DayOfWeek'] = airlines_df['DayOfWeek'].map(days) - already updated in CSV
airlines_df

       Airline  Delay AirportFrom AirportTo  DayOfWeek  Length
0           CO      1         SFO       IAH  Wednesday     205
1           US      1         PHX       CLT  Wednesday     222
2           AA      1         LAX       DFW  Wednesday     165
3           AA      1         SFO       DFW  Wednesday     195
4           AS      0         ANC       SEA  Wednesday     202
...        ...    ...         ...       ...        ...     ...
539378      CO      0         OGG       SNA     Friday     326
539379      FL      0         SEA       ATL     Friday     305
539380      FL      0         SFO       MKE     Friday     255
539381      UA      1         HNL       SFO     Friday     313
539382      US      1         LAX       PHL     Friday     301

[539383 rows x 6 columns]

In [18]:
# Create our features
# Convert string columns to numbers and drop 'delay' column then assign to X
X = pd.get_dummies(airlines_df, columns=['Airline', 'AirportFrom', 'AirportTo', 'DayOfWeek',]).drop('Delay', axis=1)
X

,Length,Airline_9E,Airline_AA,Airline_AS,Airline_B6,Airline_CO,Airline_DL,Airline_EV,Airline_F9,Airline_FL,...,AirportTo_XNA,AirportTo_YAK,AirportTo_YUM,DayOfWeek_Friday,DayOfWeek_Monday,DayOfWeek_Saturday,DayOfWeek_Sunday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,205,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,222,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,165,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,195,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,202,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539378,326,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
539379,305,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
539380,255,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
539381,313,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
539382,301,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [19]:
X.shape

(539383, 612)

In [20]:
# Create our target
y = airlines_df['Delay']
X.head()

,Length,Airline_9E,Airline_AA,Airline_AS,Airline_B6,Airline_CO,Airline_DL,Airline_EV,Airline_F9,Airline_FL,...,AirportTo_XNA,AirportTo_YAK,AirportTo_YUM,DayOfWeek_Friday,DayOfWeek_Monday,DayOfWeek_Saturday,DayOfWeek_Sunday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,205,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,222,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,165,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,195,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,202,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [21]:
X.describe()

,Length,Airline_9E,Airline_AA,Airline_AS,Airline_B6,Airline_CO,Airline_DL,Airline_EV,Airline_F9,Airline_FL,...,AirportTo_XNA,AirportTo_YAK,AirportTo_YUM,DayOfWeek_Friday,DayOfWeek_Monday,DayOfWeek_Saturday,DayOfWeek_Sunday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
count,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,...,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000,539383.000000
mean,132.202007,0.038351,0.084645,0.021267,0.033579,0.039152,0.112981,0.051880,0.011969,0.038613,...,0.002082,0.000106,0.000627,0.158047,0.134912,0.109303,0.129554,0.169536,0.132262,0.166386
std,70.117016,0.192043,0.278353,0.144273,0.180143,0.193957,0.316570,0.221784,0.108747,0.192670,...,0.045582,0.010279,0.025025,0.364786,0.341629,0.312019,0.335812,0.375225,0.338776,0.372427
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,81.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,115.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,655.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [22]:
y.value_counts()

0    299119
1    240264
Name: Delay, dtype: int64

In [23]:
## Labels are the values we want to predict
#labels = np.array(X['Delay'])

# Remove the labels from the features
# axis 1 refers to the columns
#X = X.drop('Delay', axis = 1)
# Saving feature names for later use
#X_list = list(X.columns)
# Convert to numpy array
#X = np.array(X)

In [24]:
#d = {}    
# airlines_df = airlines_df.replace(x)

# Split into training and testing splits

In [64]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
from collections import Counter


# Split the data into training and testing sets - used random_state to make the data reproducible and ensure that same rows are assigned to train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=None, test_size= 0.3)

In [65]:
# Initial imports.
import pandas as pd
from path import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [66]:
# Creating a StandardScaler instance.
#scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
#X_scaler = scaler.fit(X_train)

# Scaling the data.
#X_train_scaled = X_scaler.transform(X_train)
#X_test_scaled = X_scaler.transform(X_test)

In [68]:
#Check balances
print(Counter(y_train))
print(Counter(y_test))

Counter({0: 209318, 1: 168250})
Counter({0: 89801, 1: 72014})

# Ensemble Learners
## Used to compare which algorithm results in best performance
## Chosen in an effort to improve the accuracy and robustness of the model, decrease variance of the model, and increase overall performance of the model

# Random Forest Classifier
## Chosen to rank importance of input variables, run efficiently on large datasets, and are robust against overfitting

In [69]:
# sample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
random_f = RandomForestClassifier(n_estimators = 128, random_state=42)

In [70]:
#Fit the model
random_f = random_f.fit(X_train, y_train, sample_weight=None)

In [71]:
# Making predictions using the testing data.
predictions = random_f.predict(X_test)
predictions

array([0, 0, 0, ..., 1, 1, 1])

In [72]:
# Calculated the balanced accuracy score
y_pred = random_f.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6045733905724486

In [73]:
# Display the confusion matrix
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[59779, 30022],
       [32877, 39137]])

In [74]:
#Create dataframe for the cm 
cm_df = pd.DataFrame(
    cm, index=["Actual Not_Delayed", "Actual Delayed"], columns=["Predicted Not_Delayed", "Predicted Delayed"])
cm_df

                    Predicted Not_Delayed  Predicted Delayed
Actual Not_Delayed                  59779              30022
Actual Delayed                      32877              39137

In [75]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, y_pred)
acc_score

0.6112906714457869

In [76]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, y_pred))

Confusion Matrix

                    Predicted Not_Delayed  Predicted Delayed
Actual Not_Delayed                  59779              30022
Actual Delayed                      32877              39137

Accuracy Score : 0.6112906714457869
Classification Report
              precision    recall  f1-score   support

           0       0.65      0.67      0.66     89801
           1       0.57      0.54      0.55     72014

    accuracy                           0.61    161815
   macro avg       0.61      0.60      0.60    161815
weighted avg       0.61      0.61      0.61    161815

In [77]:
# Calculate feature importance in the Random Forest model.
importances = random_f.feature_importances_
importances

array([4.56885434e-01, 1.97719920e-03, 3.17505850e-03, 1.97365751e-03,
       1.84696399e-03, 4.64097713e-03, 4.00590263e-03, 2.13663990e-03,
       1.13020722e-03, 4.77430740e-03, 7.17847498e-04, 3.84147271e-03,
       3.98777219e-03, 3.14787724e-03, 5.46297359e-03, 5.13468511e-03,
       6.37096440e-02, 2.46559182e-03, 5.31822288e-03, 2.58092642e-04,
       9.29712892e-05, 1.06397379e-03, 3.94302402e-06, 4.78758243e-05,
       2.51559513e-05, 1.11778643e-04, 4.19384748e-05, 1.36452536e-05,
       2.77003263e-05, 1.61491709e-04, 1.40268636e-04, 7.48388464e-04,
       2.57287624e-04, 3.47088499e-04, 1.91286592e-04, 2.81420491e-03,
       2.67971184e-04, 1.45286131e-03, 2.68282184e-04, 1.44892955e-04,
       1.60375477e-04, 1.10230973e-03, 6.91334688e-05, 1.50491943e-04,
       5.77394948e-05, 4.51116735e-05, 8.21923269e-04, 2.13125169e-04,
       2.23621313e-04, 3.93182155e-05, 1.66024939e-05, 2.86984413e-04,
       1.45843048e-03, 5.58860142e-04, 2.26544371e-03, 5.80186416e-05,
       9.99692911e-05, 8.03519855e-05, 6.78497321e-05, 4.10600504e-05,
       2.51401959e-04, 4.59733395e-04, 1.03569710e-03, 5.36405588e-04,
       2.33941932e-03, 2.55901220e-04, 3.78517174e-04, 4.78898410e-04,
       5.14146906e-05, 2.66905091e-05, 5.83435090e-05, 1.58789754e-04,
       6.34557494e-05, 5.89973265e-04, 5.14167843e-05, 3.63176930e-04,
       4.09357401e-05, 1.54938567e-03, 3.33900482e-05, 2.32690535e-03,
       1.41154583e-03, 7.79483683e-05, 3.72817663e-05, 8.35819781e-05,
       4.05735888e-04, 3.44964709e-05, 1.11203778e-04, 1.79495625e-04,
       3.55954885e-04, 9.60416271e-05, 1.52759846e-03, 4.72014774e-05,
       2.03280723e-05, 1.24514802e-04, 1.67699597e-03, 8.21379341e-04,
       2.44046979e-05, 1.77874282e-03, 2.42537052e-03, 2.16849499e-03,
       1.07691072e-04, 1.95033342e-04, 7.85676399e-05, 6.97183176e-04,
       2.63922283e-03, 6.19785843e-05, 4.62911171e-04, 2.54934097e-04,
       5.61873127e-05, 9.47258103e-05, 6.27155799e-04, 4.36337583e-05,
       1.71038256e-04, 2.09317267e-04, 7.83785949e-05, 1.82306212e-03,
       1.15679931e-04, 8.82099586e-05, 3.10387393e-04, 3.38274793e-04,
       1.41638293e-04, 1.33117570e-04, 3.80627041e-05, 1.67671231e-03,
       3.26861260e-05, 3.54722619e-04, 3.46265628e-04, 9.69911202e-05,
       2.84174581e-04, 1.10156209e-04, 7.36693326e-04, 8.65046414e-05,
       2.90252924e-05, 2.15291433e-04, 8.95833578e-05, 2.55909747e-04,
       2.95334457e-04, 1.00556466e-04, 7.90215221e-04, 4.84374599e-04,
       4.34750280e-04, 1.10765787e-04, 5.98835033e-05, 8.26287124e-05,
       1.40742048e-05, 1.59505004e-04, 1.06060354e-04, 8.97089890e-04,
       1.73503724e-03, 3.32732047e-04, 2.16406882e-04, 5.18189619e-04,
       2.61139837e-05, 1.61543655e-03, 2.36651158e-03, 4.66657133e-04,
       1.21415746e-04, 1.58276273e-04, 1.59990050e-03, 5.98476598e-05,
       2.53452089e-04, 6.64522150e-05, 6.62243309e-05, 4.88117754e-05,
       2.80538808e-04, 4.76262964e-04, 1.14719503e-03, 1.83740948e-03,
       9.19224016e-05, 3.43610694e-04, 6.26070140e-05, 1.50106660e-04,
       2.52737126e-03, 3.05160755e-03, 2.94597274e-04, 5.40469227e-05,
       5.41288970e-04, 2.22125119e-04, 1.82639334e-03, 3.50596119e-04,
       3.07681339e-04, 7.85290254e-04, 6.24224347e-05, 1.38321680e-04,
       8.87456377e-05, 1.12525158e-04, 7.25496046e-05, 5.77841968e-05,
       7.06165195e-05, 3.48704625e-04, 1.64603580e-04, 1.50474046e-03,
       2.81381096e-03, 3.45952195e-04, 4.15782134e-03, 4.66416634e-05,
       1.57337539e-03, 2.68566471e-04, 1.91175400e-04, 1.48397330e-04,
       8.52661863e-05, 7.66478848e-04, 1.29594101e-03, 1.55419046e-03,
       3.39997791e-05, 1.08376429e-04, 3.55707876e-04, 1.64937411e-04,
       2.73105290e-05, 2.31722831e-04, 4.82028163e-05, 1.48717975e-04,
       9.17539874e-05, 1.68503626e-04, 6.25958652e-04, 8.30014851e-05,
       2.38785754e-03, 1.44320162e-03, 1.78318958e-04, 1.43994873e-04,
       7.78247779e-05, 1.90555093e-03, 6.11567810e-04, 1.03112498e-03,
       1.11165750e-03, 6.60825009e-05, 7.11384881e-04, 5.02108788e-03,
       9.03690877e-04, 6.37438812e-05, 7.96487668e-05, 4.42918953e-05,
       9.67264302e-04, 1.27801189e-03, 3.13084757e-04, 1.82995513e-03,
       2.41661321e-03, 2.03059902e-04, 2.46694155e-05, 4.61179366e-05,
       1.68896775e-03, 4.44060664e-05, 3.47374808e-04, 1.49119794e-04,
       7.00559921e-05, 2.95113878e-05, 4.60718476e-04, 8.30269707e-04,
       3.24082230e-04, 2.65127001e-04, 5.82515530e-05, 1.77027758e-04,
       1.61406884e-03, 7.85489906e-04, 1.05535234e-04, 6.75028314e-04,
       2.52237626e-04, 8.26636168e-04, 2.92478963e-05, 1.50422346e-04,
       1.29357932e-03, 4.76331681e-05, 1.52314286e-03, 1.23807052e-03,
       4.99330567e-04, 2.46821185e-04, 2.86904779e-04, 1.11100200e-04,
       2.62750235e-05, 5.02628306e-05, 9.71150006e-04, 1.78738577e-03,
       2.88161560e-03, 2.73288051e-04, 5.80358834e-05, 2.12890964e-04,
       3.29871374e-05, 1.00051937e-03, 9.37393106e-06, 7.62032067e-04,
       2.02054586e-03, 1.18042189e-03, 5.99413004e-05, 1.30959343e-03,
       9.50642612e-05, 3.57380163e-05, 3.00538203e-04, 1.89121208e-03,
       2.54902794e-04, 5.02137499e-05, 7.96891042e-05, 1.82460452e-04,
       8.50817470e-04, 1.91788544e-05, 2.38665852e-04, 4.45270787e-05,
       1.89166008e-03, 1.86481964e-04, 9.82265720e-04, 8.45730497e-04,
       1.82328611e-04, 8.86519323e-05, 3.60903547e-05, 1.89616096e-05,
       6.60255973e-04, 2.16464004e-05, 7.24904551e-05, 2.31101537e-04,
       2.87126661e-05, 5.22515527e-04, 3.38001543e-05, 1.02185915e-04,
       2.82127608e-04, 3.96316334e-05, 9.41635416e-04, 4.39562159e-06,
       5.81599209e-05, 2.47028243e-05, 1.03576813e-04, 3.80697969e-05,
       6.36478585e-06, 2.72732950e-05, 1.43729243e-04, 1.15016417e-04,
       6.33511923e-04, 2.23679064e-04, 3.29889799e-04, 1.86439275e-04,
       3.04416916e-03, 3.20363429e-04, 1.42673322e-03, 2.15698713e-04,
       1.32218255e-04, 1.78844698e-04, 1.15350136e-03, 4.11934584e-05,
       1.45415484e-04, 7.12903066e-05, 4.10885136e-05, 7.64979415e-04,
       1.75972899e-04, 2.18569487e-04, 5.45457711e-05, 1.84761151e-05,
       2.82607756e-04, 1.59539288e-03, 5.44819144e-04, 2.26267009e-03,
       4.95203817e-05, 1.28038645e-04, 9.42490405e-05, 2.97742561e-05,
       5.29604142e-05, 2.16638464e-04, 4.04050764e-04, 1.04443217e-03,
       5.53451775e-04, 1.78653286e-03, 2.57147540e-04, 3.74669804e-04,
       4.29734898e-04, 3.64716113e-05, 3.69644807e-05, 4.75383561e-05,
       2.08550486e-04, 5.72585175e-05, 6.59344764e-04, 3.45086027e-05,
       3.52348452e-04, 5.53427979e-05, 1.50688931e-03, 3.24376531e-05,
       1.78438065e-03, 1.25240527e-03, 1.01842334e-04, 4.23377389e-05,
       7.76767018e-05, 3.35252851e-04, 4.08742271e-05, 1.26313098e-04,
       1.14225955e-04, 3.25625880e-04, 7.64552684e-05, 1.62566756e-03,
       5.52531998e-05, 4.00480507e-05, 1.19567265e-04, 6.19441138e-04,
       7.94396503e-04, 3.00621577e-05, 1.75263170e-03, 2.79880108e-03,
       3.73171998e-03, 5.28409922e-05, 1.71221455e-04, 7.72408722e-05,
       5.93262640e-04, 2.46190656e-03, 6.22314463e-05, 3.07713998e-04,
       2.56251847e-04, 4.55903104e-05, 6.25885469e-05, 6.24900737e-04,
       4.65334359e-05, 1.70509291e-04, 2.24724856e-04, 6.17836318e-05,
       1.95068838e-03, 1.59537717e-04, 1.22385683e-04, 3.21262717e-04,
       4.16508407e-04, 1.26707136e-04, 1.22779185e-04, 3.32711024e-05,
       1.71182811e-03, 4.38391277e-05, 3.30196526e-04, 3.52696583e-04,
       6.77678335e-05, 2.83766946e-04, 1.31741096e-04, 5.44066570e-04,
       7.87542116e-05, 2.45818475e-05, 1.60803463e-04, 7.00749634e-05,
       2.89331079e-04, 3.41887077e-04, 1.24790346e-04, 7.97162397e-04,
       4.96762108e-04, 4.33517402e-04, 9.70898488e-05, 7.67389226e-05,
       1.19828319e-04, 1.73315061e-05, 1.29546406e-04, 1.05897007e-04,
       8.38745846e-04, 1.10955274e-03, 3.88917098e-04, 1.66643848e-04,
       4.76258535e-04, 3.01899980e-05, 1.62857318e-03, 2.18468853e-03,
       4.84984893e-04, 9.18118384e-05, 1.36603544e-04, 1.50486280e-03,
       5.02435812e-05, 2.08749676e-04, 4.95590280e-05, 5.67812686e-05,
       4.85261386e-05, 2.79545142e-04, 3.96301677e-04, 1.10120973e-03,
       2.06724468e-03, 9.65705388e-05, 2.78943722e-04, 6.66244588e-05,
       1.92830322e-04, 2.58573997e-03, 2.52302535e-03, 2.61732309e-04,
       4.74439079e-05, 5.43832005e-04, 1.71083630e-04, 1.89363439e-03,
       4.04724803e-04, 2.23141006e-04, 7.34590341e-04, 5.35769537e-05,
       1.56109477e-04, 8.41566475e-05, 1.33961547e-04, 6.50336096e-05,
       5.30479199e-05, 5.32106408e-05, 2.89880931e-04, 1.83049177e-04,
       1.50769071e-03, 2.59683391e-03, 3.70148708e-04, 1.81575641e-03,
       5.12411000e-05, 1.65124371e-03, 2.43820273e-04, 1.81439808e-04,
       1.39279331e-04, 9.34380666e-05, 5.62164797e-04, 1.44601062e-03,
       1.32212335e-03, 3.58735336e-05, 9.14884962e-05, 3.74417411e-04,
       1.46664913e-04, 3.34147316e-05, 1.86310520e-04, 3.50887123e-05,
       1.09190297e-04, 1.11901461e-04, 1.61610825e-04, 6.27462435e-04,
       1.40473457e-04, 2.15759094e-03, 1.45137961e-03, 1.47881050e-04,
       1.39219074e-04, 8.01005781e-05, 1.08750125e-03, 4.64681345e-04,
       9.63399595e-04, 9.85983273e-04, 9.73886763e-05, 6.58626704e-04,
       2.96509245e-03, 8.84087250e-04, 7.40327049e-05, 7.60528957e-05,
       4.49375320e-05, 9.26873611e-04, 1.38236321e-03, 2.70999262e-04,
       1.88724832e-03, 2.60751937e-03, 1.95115995e-04, 3.40096027e-05,
       6.79024858e-05, 1.58654613e-03, 3.50683083e-05, 4.05951128e-04,
       1.59154727e-04, 7.58608914e-05, 2.72634208e-05, 4.38977116e-04,
       6.54768180e-04, 4.15698746e-04, 2.76633983e-04, 5.02271053e-05,
       1.56249199e-04, 1.58250111e-03, 8.04357414e-04, 1.36881989e-04,
       7.38172116e-04, 1.98917778e-04, 7.93803203e-04, 6.70456559e-05,
       1.29822888e-04, 1.13604210e-03, 4.52273063e-05, 1.60860151e-03,
       1.17942493e-03, 4.64572592e-04, 2.15407638e-04, 2.76334028e-04,
       1.19380251e-04, 4.27707229e-05, 7.79149142e-05, 9.35236927e-04,
       1.76876590e-03, 2.37151869e-03, 3.71152657e-04, 7.23681938e-05,
       1.96724145e-04, 4.48975569e-05, 9.15364659e-04, 4.40775986e-05,
       9.62483066e-04, 1.82892668e-03, 1.03336224e-03, 6.27482659e-05,
       1.06640357e-03, 8.18636074e-05, 3.09168418e-05, 3.33677392e-04,
       1.76440490e-03, 2.56147530e-04, 6.99347548e-05, 5.50679526e-05,
       1.38504398e-04, 6.87000276e-04, 1.65525173e-05, 2.63444277e-04,
       3.25226382e-05, 1.88822008e-03, 1.70529031e-04, 9.11794919e-04,
       7.87344126e-04, 2.17312910e-04, 5.83532845e-05, 3.22238467e-05,
       2.87166201e-05, 6.61643763e-04, 1.86102860e-05, 6.61964190e-05,
       2.38180667e-04, 2.35531908e-05, 5.67828668e-04, 3.34393190e-05,
       1.06850927e-04, 1.47576737e-02, 1.76451913e-02, 1.20627349e-02,
       1.77736461e-02, 1.91477342e-02, 1.87993889e-02, 1.59372615e-02])

In [78]:
# We can sort the features by their importance.
sorted(zip(random_f.feature_importances_, X.columns), reverse=True)

[(0.45688543449091334, 'Length'),
 (0.06370964404935864, 'Airline_WN'),
 (0.019147734221829665, 'DayOfWeek_Thursday'),
 (0.018799388931829975, 'DayOfWeek_Tuesday'),
 (0.017773646087613528, 'DayOfWeek_Sunday'),
 (0.017645191297543987, 'DayOfWeek_Monday'),
 (0.015937261469867566, 'DayOfWeek_Wednesday'),
 (0.014757673710975914, 'DayOfWeek_Friday'),
 (0.012062734901788419, 'DayOfWeek_Saturday'),
 (0.005462973589413295, 'Airline_UA'),
 (0.0053182228838776924, 'Airline_YV'),
 (0.00513468510907757, 'Airline_US'),
 (0.005021087875409323, 'AirportFrom_ORD'),
 (0.004774307402136019, 'Airline_FL'),
 (0.004640977134271785, 'Airline_CO'),
 (0.004157821343145359, 'AirportFrom_MDW'),
 (0.004005902631075975, 'Airline_DL'),
 (0.003987772189768624, 'Airline_OH'),
 (0.0038414727106356613, 'Airline_MQ'),
 (0.003731719978276882, 'AirportTo_DFW'),
 (0.0031750584994072986, 'Airline_AA'),
 (0.0031478772369977343, 'Airline_OO'),
 (0.0030516075456975982, 'AirportFrom_LAX'),
 (0.0030441691632468936, 'AirportTo_ATL'),
 (0.002965092448665174, 'AirportTo_ORD'),
 (0.0028816155967948745, 'AirportFrom_SFO'),
 (0.0028142049081179526, 'AirportFrom_ATL'),
 (0.0028138109561494117, 'AirportFrom_MCO'),
 (0.0027988010836112235, 'AirportTo_DEN'),
 (0.002639222828260927, 'AirportFrom_DTW'),
 (0.002607519365745578, 'AirportTo_PHX'),
 (0.002596833910618968, 'AirportTo_MCO'),
 (0.002585739967061514, 'AirportTo_LAS'),
 (0.002527371256551799, 'AirportFrom_LAS'),
 (0.002523025350197962, 'AirportTo_LAX'),
 (0.0024655918231251254, 'Airline_XE'),
 (0.0024619065556975087, 'AirportTo_DTW'),
 (0.0024253705190112424, 'AirportFrom_DEN'),
 (0.00241661321216534, 'AirportFrom_PHX'),
 (0.0023878575373012328, 'AirportFrom_MSP'),
 (0.0023715186938054657, 'AirportTo_SFO'),
 (0.002366511583516204, 'AirportFrom_IAH'),
 (0.0023394193223567226, 'AirportFrom_BWI'),
 (0.0023269053487382906, 'AirportFrom_CLT'),
 (0.0022654437137060463, 'AirportFrom_BOS'),
 (0.002262670090165277, 'AirportTo_BOS'),
 (0.002184688530346632, 'AirportTo_IAH'),
 (0.0021684949905526316, 'AirportFrom_DFW'),
 (0.002157590938817768, 'AirportTo_MSP'),
 (0.002136639899287839, 'Airline_EV'),
 (0.002067244679518284, 'AirportTo_JFK'),
 (0.002020545857189921, 'AirportFrom_SLC'),
 (0.0019771991999028987, 'Airline_9E'),
 (0.001973657509144987, 'Airline_AS'),
 (0.0019506883786017627, 'AirportTo_EWR'),
 (0.0019055509295597746, 'AirportFrom_OAK'),
 (0.0018936343869857559, 'AirportTo_LGA'),
 (0.0018916600765206835, 'AirportFrom_TPA'),
 (0.00189121208305561, 'AirportFrom_STL'),
 (0.0018882200804008198, 'AirportTo_TPA'),
 (0.0018872483239212542, 'AirportTo_PHL'),
 (0.0018469639892775367, 'Airline_B6'),
 (0.0018374094821288192, 'AirportFrom_JFK'),
 (0.0018299551268722335, 'AirportFrom_PHL'),
 (0.0018289266789536147, 'AirportTo_SLC'),
 (0.0018263933377806129, 'AirportFrom_LGA'),
 (0.001823062122881725, 'AirportFrom_EWR'),
 (0.0018157564078394623, 'AirportTo_MDW'),
 (0.001787385769748416, 'AirportFrom_SEA'),
 (0.0017865328600327655, 'AirportTo_BWI'),
 (0.0017843806471777262, 'AirportTo_CLT'),
 (0.0017787428229656546, 'AirportFrom_DCA'),
 (0.001768765897808468, 'AirportTo_SEA'),
 (0.0017644048984409863, 'AirportTo_STL'),
 (0.001752631696984843, 'AirportTo_DCA'),
 (0.0017350372362102148, 'AirportFrom_HOU'),
 (0.001711828107076748, 'AirportTo_FLL'),
 (0.0016889677545764057, 'AirportFrom_PIT'),
 (0.001676995965479081, 'AirportFrom_DAL'),
 (0.0016767123053640874, 'AirportFrom_FLL'),
 (0.0016512437069434564, 'AirportTo_MEM'),
 (0.0016285731769916302, 'AirportTo_IAD'),
 (0.0016256675600828843, 'AirportTo_CVG'),
 (0.001615436552021216, 'AirportFrom_IAD'),
 (0.0016140688389740879, 'AirportFrom_RDU'),
 (0.0016086015112089975, 'AirportTo_SAN'),
 (0.0015999005042790218, 'AirportFrom_IND'),
 (0.0015953928849709313, 'AirportTo_BNA'),
 (0.0015865461282202516, 'AirportTo_PIT'),
 (0.0015825011127542361, 'AirportTo_RDU'),
 (0.0015733753891703456, 'AirportFrom_MEM'),
 (0.0015541904562547447, 'AirportFrom_MKE'),
 (0.0015493856678531087, 'AirportFrom_CLE'),
 (0.0015275984568947196, 'AirportFrom_CVG'),
 (0.0015231428585820016, 'AirportFrom_SAN'),
 (0.0015076907137364657, 'AirportTo_MCI'),
 (0.001506889306054824, 'AirportTo_CLE'),
 (0.0015048628048426362, 'AirportTo_IND'),
 (0.0015047404551363746, 'AirportFrom_MCI'),
 (0.0014584304769310677, 'AirportFrom_BNA'),
 (0.001452861310922178, 'AirportFrom_AUS'),
 (0.0014513796076494167, 'AirportTo_MSY'),
 (0.0014460106155752672, 'AirportTo_MIA'),
 (0.0014432016239405172, 'AirportFrom_MSY'),
 (0.0014267332163249162, 'AirportTo_AUS'),
 (0.0014115458295974287, 'AirportFrom_CMH'),
 (0.0013823632063698712, 'AirportTo_PDX'),
 (0.0013221233454962314, 'AirportTo_MKE'),
 (0.001309593428105246, 'AirportFrom_SNA'),
 (0.001295941010086657, 'AirportFrom_MIA'),
 (0.0012935793224016269, 'AirportFrom_RSW'),
 (0.0012780118900011185, 'AirportFrom_PDX'),
 (0.0012524052692007193, 'AirportTo_CMH'),
 (0.001238070519656647, 'AirportFrom_SAT'),
 (0.001180421886256498, 'AirportFrom_SMF'),
 (0.001179424927248837, 'AirportTo_SAT'),
 (0.0011535013596233404, 'AirportTo_BDL'),
 (0.0011471950341550461, 'AirportFrom_JAX'),
 (0.0011360421040353004, 'AirportTo_RSW'),
 (0.0011302072150482653, 'Airline_F9'),
 (0.0011116575037392333, 'AirportFrom_OMA'),
 (0.0011095527377772128, 'AirportTo_HOU'),
 (0.001102309734833552, 'AirportFrom_BDL'),
 (0.001101209734206583, 'AirportTo_JAX'),
 (0.0010875012503577715, 'AirportTo_OAK'),
 (0.001066403568898811, 'AirportTo_SNA'),
 (0.0010639737917038435, 'AirportFrom_ABQ'),
 (0.0010444321745537314, 'AirportTo_BUF'),
 (0.0010356970995504245, 'AirportFrom_BUF'),
 (0.0010333622436360047, 'AirportTo_SMF'),
 (0.0010311249759890981, 'AirportFrom_OKC'),
 (0.0010005193683022477, 'AirportFrom_SJC'),
 (0.0009859832727854019, 'AirportTo_OMA'),
 (0.000982265719688437, 'AirportFrom_TUL'),
 (0.0009711500057691833, 'AirportFrom_SDF'),
 (0.0009672643018167013, 'AirportFrom_PBI'),
 (0.0009633995954937517, 'AirportTo_OKC'),
 (0.0009624830656591798, 'AirportTo_SJU'),
 (0.0009416354158324539, 'AirportTo_ABQ'),
 (0.0009352369270943629, 'AirportTo_SDF'),
 (0.0009268736106190165, 'AirportTo_PBI'),
 (0.0009153646593713503, 'AirportTo_SJC'),
 (0.0009117949189324621, 'AirportTo_TUL'),
 (0.0009036908772270657, 'AirportFrom_ORF'),
 (0.0008970898900097893, 'AirportFrom_HNL'),
 (0.0008840872500966598, 'AirportTo_ORF'),
 (0.0008508174697023819, 'AirportFrom_SYR'),
 (0.0008457304971465985, 'AirportFrom_TUS'),
 (0.0008387458464856111, 'AirportTo_HNL'),
 (0.0008302697066362699, 'AirportFrom_PVD'),
 (0.0008266361678634935, 'AirportFrom_ROC'),
 (0.0008219232692370793, 'AirportFrom_BHM'),
 (0.0008213793406073392, 'AirportFrom_DAY'),
 (0.000804357413520059, 'AirportTo_RIC'),
 (0.0007971623966865458, 'AirportTo_GRR'),
 (0.000794396502987021, 'AirportTo_DAY'),
 (0.0007938032034225987, 'AirportTo_ROC'),
 (0.0007902152206923419, 'AirportFrom_GRR'),
 (0.0007873441257336901, 'AirportTo_TUS'),
 (0.0007854899060630852, 'AirportFrom_RIC'),
 (0.0007852902541347633, 'AirportFrom_LIT'),
 (0.0007664788477560849, 'AirportFrom_MHT'),
 (0.0007649794149161683, 'AirportTo_BHM'),
 (0.000762032066909236, 'AirportFrom_SJU'),
 (0.0007483884635496417, 'AirportFrom_ALB'),
 (0.0007381721163996924, 'AirportTo_RNO'),
 (0.0007366933259546447, 'AirportFrom_GEG'),
 (0.0007345903409702567, 'AirportTo_LIT'),
 (0.0007178474978055282, 'Airline_HA'),
 (0.0007113848807334137, 'AirportFrom_ONT'),
 (0.0006971831760365218, 'AirportFrom_DSM'),
 (0.0006870002756141335, 'AirportTo_SYR'),
 (0.0006750283135477502, 'AirportFrom_RNO'),
 (0.0006616437632662643, 'AirportTo_TYS'),
 (0.000660255973159704, 'AirportFrom_TYS'),
 (0.0006593447637740093, 'AirportTo_CHS'),
 (0.0006586267038713976, 'AirportTo_ONT'),
 (0.0006547681800737283, 'AirportTo_PVD'),
 (0.000633511922604552, 'AirportTo_ALB'),
 (0.0006274624347237148, 'AirportTo_MSN'),
 (0.0006271557992422302, 'AirportFrom_ELP'),
 (0.0006259586523259169, 'AirportFrom_MSN'),
 (0.0006249007374560108, 'AirportTo_ELP'),
 (0.0006194411377320753, 'AirportTo_DAL'),
 (0.0006115678103372914, 'AirportFrom_OGG'),
 (0.0005932626402119572, 'AirportTo_DSM'),
 (0.0005899732648315966, 'AirportFrom_CHS'),
 (0.0005678286680773484, 'AirportTo_XNA'),
 (0.0005621647972352007, 'AirportTo_MHT'),
 (0.0005588601421583574, 'AirportFrom_BOI'),
 (0.0005534517748149758, 'AirportTo_BUR'),
 (0.0005448191435257141, 'AirportTo_BOI'),
 (0.0005440665699794261, 'AirportTo_GEG'),
 (0.0005438320047962048, 'AirportTo_LEX'),
 (0.0005412889695684262, 'AirportFrom_LEX'),
 (0.0005364055877430709, 'AirportFrom_BUR'),
 (0.0005225155269855612, 'AirportFrom_XNA'),
 (0.0005181896188543361, 'AirportFrom_HSV'),
 (0.0004993305667243741, 'AirportFrom_SAV'),
 (0.000496762107843661, 'AirportTo_GSO'),
 (0.0004849848930496013, 'AirportTo_ICT'),
 (0.0004843745986379561, 'AirportFrom_GSO'),
 (0.0004788984104072742, 'AirportFrom_CAK'),
 (0.00047626296362163255, 'AirportFrom_JAN'),
 (0.00047625853491307224, 'AirportTo_HSV'),
 (0.00046665713313701735, 'AirportFrom_ICT'),
 (0.0004646813453228844, 'AirportTo_OGG'),
 (0.00046457259171996964, 'AirportTo_SAV'),
 (0.0004629111706179366, 'AirportFrom_ECP'),
 (0.0004607184758030912, 'AirportFrom_PSP'),
 (0.0004597333947991756, 'AirportFrom_BTV'),
 (0.0004389771156827569, 'AirportTo_PSP'),
 (0.000434750280223496, 'AirportFrom_GSP'),
 (0.0004335174018569213, 'AirportTo_GSP'),
 (0.0004297348984455342, 'AirportTo_CAK'),
 (0.0004165084071570207, 'AirportTo_FAT'),
 (0.00041569874625589144, 'AirportTo_PWM'),
 (0.00040595112794169103, 'AirportTo_PNS'),
 (0.00040573588828545334, 'AirportFrom_COS'),
 (0.0004047248034956504, 'AirportTo_LGB'),
 (0.0004040507635213598, 'AirportTo_BTV'),
 (0.00039630167733272203, 'AirportTo_JAN'),
 (0.000388917098090643, 'AirportTo_HPN'),
 (0.00037851717383268163, 'AirportFrom_CAE'),
 (0.00037466980395485776, 'AirportTo_CAE'),
 (0.0003744174109322257, 'AirportTo_MLI'),
 (0.00037115265678639017, 'AirportTo_SGF'),
 (0.00037014870799621406, 'AirportTo_MDT'),
 (0.0003631769303514631, 'AirportFrom_CID'),
 (0.00035595488485156546, 'AirportFrom_CRW'),
 (0.0003557078758896214, 'AirportFrom_MLI'),
 (0.0003547226190616467, 'AirportFrom_FNT'),
 (0.0003526965832223744, 'AirportTo_FSD'),
 (0.0003523484518536161, 'AirportTo_CID'),
 (0.00035059611910089907, 'AirportFrom_LGB'),
 (0.00034870462533026487, 'AirportFrom_MAF'),
 (0.0003473748081506291, 'AirportFrom_PNS'),
 (0.0003470884990760531, 'AirportFrom_ANC'),
 (0.00034626562814015757, 'AirportFrom_FSD'),
 (0.0003459521948198544, 'AirportFrom_MDT'),
 (0.00034361069367078205, 'AirportFrom_KOA'),
 (0.0003418870773461454, 'AirportTo_GRB'),
 (0.0003382747929624545, 'AirportFrom_FAT'),
 (0.00033525285103562253, 'AirportTo_COS'),
 (0.0003336773918613955, 'AirportTo_SRQ'),
 (0.0003327320472965082, 'AirportFrom_HPN'),
 (0.00033019652599084403, 'AirportTo_FNT'),
 (0.000329889798804231, 'AirportTo_ANC'),
 (0.00032562588000410617, 'AirportTo_CRW'),
 (0.0003240822296608245, 'AirportFrom_PWM'),
 (0.000321262717323897, 'AirportTo_FAR'),
 (0.00032036342861383826, 'AirportTo_ATW'),
 (0.0003130847573807068, 'AirportFrom_PHF'),
 (0.0003103873930008605, 'AirportFrom_FAR'),
 (0.000307713998126297, 'AirportTo_ECP'),
 (0.0003076813389415301, 'AirportFrom_LIH'),
 (0.0003005382031243567, 'AirportFrom_SRQ'),
 (0.0002953344565583526, 'AirportFrom_GRB'),
 (0.00029459727362066536, 'AirportFrom_LBB'),
 (0.0002898809308308513, 'AirportTo_MAF'),
 (0.0002893310787715799, 'AirportTo_GPT'),
 (0.0002869844125710483, 'AirportFrom_BMI'),
 (0.0002869047794352478, 'AirportFrom_SBN'),
 (0.0002841745807604268, 'AirportFrom_FWA'),
 (0.00028376694589487823, 'AirportTo_FWA'),
 (0.0002826077563535118, 'AirportTo_BMI'),
 (0.00028212760795270724, 'AirportTo_ABE'),
 (0.00028053880794004965, 'AirportFrom_JAC'),
 (0.00027954514188617357, 'AirportTo_JAC'),
 (0.0002789437216609764, 'AirportTo_KOA'),
 (0.000276633982555998, 'AirportTo_RAP'),
 (0.0002763340282067662, 'AirportTo_SBN'),
 (0.00027328805139237034, 'AirportFrom_SGF'),
 (0.00027099926227638747, 'AirportTo_PHF'),
 (0.0002685664706436975, 'AirportFrom_MFE'),
 (0.00026828218434715343, 'AirportFrom_AVL'),
 (0.00026797118374867013, 'AirportFrom_ATW'),
 (0.00026512700125580935, 'AirportFrom_RAP'),
 (0.0002634442769198448, 'AirportTo_TLH'),
 (0.0002617323090824021, 'AirportTo_LBB'),
 (0.0002580926418181032, 'AirportFrom_ABE'),
 (0.00025728762368711105, 'AirportFrom_AMA'),
 (0.00025714754014208264, 'AirportTo_BZN'),
 (0.0002562518470516887, 'AirportTo_EGE'),
 (0.0002561475295226174, 'AirportTo_STT'),
 (0.00025590974697676854, 'AirportFrom_GPT'),
 (0.00025590121988125936, 'AirportFrom_BZN'),
 (0.0002549340965960023, 'AirportFrom_EGE'),
 (0.00025490279414680885, 'AirportFrom_STT'),
 (0.00025345208894474256, 'AirportFrom_ISP'),
 (0.00025223762646570526, 'AirportFrom_ROA'),
 (0.0002514019585445693, 'AirportFrom_BTR'),
 (0.00024682118522415295, 'AirportFrom_SBA'),
 (0.0002438202732380704, 'AirportTo_MFE'),
 (0.00023866585231176472, 'AirportFrom_TLH'),
 (0.00023818066655467414, 'AirportTo_VPS'),
 (0.0002317228310299046, 'AirportFrom_MOB'),
 (0.0002311015367294143, 'AirportFrom_VPS'),
 (0.0002247248561854901, 'AirportTo_EVV'),
 (0.00022367906445995388, 'AirportTo_AMA'),
 (0.00022362131259171693, 'AirportFrom_BIS'),
 (0.00022314100588070258, 'AirportTo_LIH'),
 (0.00022212511931016203, 'AirportFrom_LFT'),
 (0.00021856948685341894, 'AirportTo_BIS'),
 (0.0002173129096295498, 'AirportTo_TVC'),
 (0.0002166384639520335, 'AirportTo_BTR'),
 (0.00021640688225033373, 'AirportFrom_HRL'),
 (0.0002156987131356026, 'AirportTo_AVL'),
 (0.00021540763844738275, 'AirportTo_SBA'),
 (0.0002152914328851932, 'AirportFrom_GJT'),
 (0.0002131251691871139, 'AirportFrom_BIL'),
 (0.0002128909643212954, 'AirportFrom_SHV'),
 (0.00020931726657855373, 'AirportFrom_EVV'),
 (0.00020874967621505513, 'AirportTo_ISP'),
 (0.0002085504855443177, 'AirportTo_CHA'),
 (0.0002030599016181376, 'AirportFrom_PIA'),
 (0.0001989177775731097, 'AirportTo_ROA'),
 (0.00019672414476066446, 'AirportTo_SHV'),
 (0.00019511599549416748, 'AirportTo_PIA'),
 (0.0001950333420099838, 'AirportFrom_DLH'),
 (0.00019283032240693078, 'AirportTo_LAN'),
 (0.00019128659189737455, 'AirportFrom_ASE'),
 (0.0001911753999070002, 'AirportFrom_MFR'),
 (0.00018648196388447875, 'AirportFrom_TRI'),
 (0.00018643927483435067, 'AirportTo_ASE'),
 (0.00018631051987407903, 'AirportTo_MOB'),
 (0.00018304917678559453, 'AirportTo_MBS'),
 (0.0001824604522110497, 'AirportFrom_SWF'),
 (0.0001823286106687544, 'AirportFrom_TVC'),
 (0.00018143980751275575, 'AirportTo_MFR'),
 (0.00017949562485085942, 'AirportFrom_CRP'),
 (0.0001788446978444794, 'AirportTo_AZO'),
 (0.00017831895803495425, 'AirportFrom_MTJ'),
 (0.00017702775774853445, 'AirportFrom_RDM'),
 (0.0001759728990742278, 'AirportTo_BIL'),
 (0.0001712214550246223, 'AirportTo_DLH'),
 (0.0001710836304202088, 'AirportTo_LFT'),
 (0.00017103825613880899, 'AirportFrom_EUG'),
 (0.00017052903065397702, 'AirportTo_TRI'),
 (0.00017050929051485537, 'AirportTo_EUG'),
 (0.00016850362643390746, 'AirportFrom_MRY'),
 (0.00016664384760272716, 'AirportTo_HRL'),
 (0.00016493741061019885, 'AirportFrom_MLU'),
 (0.00016460358034345014, 'AirportFrom_MBS'),
 (0.00016161082457020752, 'AirportTo_MRY'),
 (0.00016149170917710662, 'AirportFrom_AEX'),
 (0.00016080346300713876, 'AirportTo_GJT'),
 (0.0001603754767313542, 'AirportFrom_AZO'),
 (0.000159537716973056, 'AirportTo_EYW'),
 (0.00015950500388692458, 'AirportFrom_HDN'),
 (0.00015915472693586475, 'AirportTo_PSC'),
 (0.0001587897537581419, 'AirportFrom_CHA'),
 (0.00015827627250761074, 'AirportFrom_ILM'),
 (0.00015624919906423736, 'AirportTo_RDM'),
 (0.0001561094768185933, 'AirportTo_LNK'),
 (0.00015049194295201909, 'AirportFrom_BFL'),
 (0.00015042234629947238, 'AirportFrom_RST'),
 (0.00015010665994088363, 'AirportFrom_LAN'),
 (0.00014911979377507694, 'AirportFrom_PSC'),
 (0.00014871797528682545, 'AirportFrom_MOT'),
 (0.00014839733044964875, 'AirportFrom_MGM'),
 (0.00014788105007270164, 'AirportTo_MTJ'),
 (0.00014666491326058385, 'AirportTo_MLU'),
 (0.0001454154836237231, 'AirportTo_BFL'),
 (0.00014489295472964526, 'AirportFrom_AVP'),
 (0.0001439948734671552, 'AirportFrom_MYR'),
 (0.00014372924302022682, 'AirportTo_AEX'),
 (0.0001416382932933683, 'AirportFrom_FAY'),
 (0.00014047345664910916, 'AirportTo_MSO'),
 (0.00014026863572772906, 'AirportFrom_AGS'),
 (0.00013927933088185297, 'AirportTo_MGM'),
 (0.0001392190744670631, 'AirportTo_MYR'),
 (0.0001385043984139778, 'AirportTo_SWF'),
 (0.0001383216795838866, 'AirportFrom_LNK'),
 (0.0001368819894224712, 'AirportTo_RKS'),
 (0.0001366035440866984, 'AirportTo_ILM'),
 (0.00013396154674894892, 'AirportTo_LSE'),
 (0.00013311756986885865, 'AirportFrom_FCA'),
 (0.00013221825547891298, 'AirportTo_AVP'),
 (0.0001317410958111142, 'AirportTo_GCC'),
 (0.00012982288816150883, 'AirportTo_RST'),
 (0.00012954640551269398, 'AirportTo_HDN'),
 (0.0001280386452459884, 'AirportTo_BQN'),
 (0.0001267071360390105, 'AirportTo_FAY'),
 (0.0001263130981983968, 'AirportTo_CPR'),
 (0.00012479034583081158, 'AirportTo_GRK'),
 (0.00012451480156217386, 'AirportFrom_DAB'),
 (0.00012277918532061118, 'AirportTo_FCA'),
 (0.0001223856830135325, 'AirportTo_FAI'),
 (0.00012141574555953543, 'AirportFrom_IDA'),
 (0.00011982831870104315, 'AirportTo_GUC'),
 (0.00011956726473297034, 'AirportTo_DAB'),
 (0.00011938025091256771, 'AirportTo_SBP'),
 (0.0001156799310683475, 'AirportFrom_EYW'),
 (0.0001150164171726218, 'AirportTo_AGS'),
 (0.00011422595542529752, 'AirportTo_CRP'),
 (0.00011252515818001165, 'AirportFrom_LSE'),
 (0.000111901460769355, 'AirportTo_MQT'),
 (0.00011177864301152755, 'AirportFrom_ACV'),
 (0.00011120377787629261, 'AirportFrom_CPR'),
 (0.00011110019966336291, 'AirportFrom_SBP'),
 (0.0001107657874119811, 'AirportFrom_GTF'),
 (0.0001101562092701016, 'AirportFrom_GCC'),
 (0.00010919029720989488, 'AirportTo_MOT'),
 (0.00010837642872843992, 'AirportFrom_MLB'),
 (0.00010769107231833124, 'AirportFrom_DHN'),
 (0.00010685092675904037, 'AirportTo_YUM'),
 (0.00010606035408739136, 'AirportFrom_HLN'),
 (0.00010589700721961017, 'AirportTo_HLN'),
 (0.00010553523384391869, 'AirportFrom_RKS'),
 (0.00010357681322239106, 'AirportTo_ACV'),
 (0.00010218591503613136, 'AirportFrom_YUM'),
 (0.00010184233416546643, 'AirportTo_CMI'),
 (0.00010055646647498764, 'AirportFrom_GRK'),
 (9.996929107518868e-05, 'AirportFrom_BQN'),
 (9.738867628826559e-05, 'AirportTo_OME'),
 (9.708984876200044e-05, 'AirportTo_GTF'),
 (9.69911202146359e-05, 'AirportFrom_FSM'),
 (9.657053878416101e-05, 'AirportTo_JNU'),
 (9.60416271331201e-05, 'AirportFrom_CSG'),
 (9.506426117833692e-05, 'AirportFrom_SPI'),
 (9.472581031377154e-05, 'AirportFrom_ELM'),
 (9.424904048617217e-05, 'AirportTo_BRO'),
 (9.343806658356285e-05, 'AirportTo_MHK'),
 (9.297128916582239e-05, 'AirportFrom_ABI'),
 (9.192240160485136e-05, 'AirportFrom_JNU'),
 (9.181183836851813e-05, 'AirportTo_IDA'),
 (9.175398739520312e-05, 'AirportFrom_MQT'),
 (9.148849618698916e-05, 'AirportTo_MLB'),
 (8.958335779417883e-05, 'AirportFrom_GNV'),
 (8.874563774620404e-05, 'AirportFrom_LRD'),
 (8.865193227978363e-05, 'AirportFrom_TWF'),
 (8.820995861379183e-05, 'AirportFrom_FAI'),
 (8.650464144550049e-05, 'AirportFrom_GFK'),
 (8.526618625866875e-05, 'AirportFrom_MHK'),
 (8.415664751834114e-05, 'AirportTo_LRD'),
 (8.358197807550282e-05, 'AirportFrom_COD'),
 (8.300148506219945e-05, 'AirportFrom_MSO'),
 (8.262871236631544e-05, 'AirportFrom_GUC'),
 (8.186360741460669e-05, 'AirportTo_SPI'),
 (8.035198547674039e-05, 'AirportFrom_BRO'),
 (8.010057808592929e-05, 'AirportTo_OAJ'),
 (7.968910416383103e-05, 'AirportFrom_SUN'),
 (7.96487668076074e-05, 'AirportFrom_OTZ'),
 (7.87542116265982e-05, 'AirportTo_GFK'),
 (7.856763988212523e-05, 'AirportFrom_DRO'),
 (7.837859493248892e-05, 'AirportFrom_EWN'),
 (7.794836832188351e-05, 'AirportFrom_CMI'),
 (7.791491424100975e-05, 'AirportTo_SCE'),
 (7.78247779425941e-05, 'AirportFrom_OAJ'),
 (7.767670183813143e-05, 'AirportTo_COD'),
 (7.724087220131512e-05, 'AirportTo_DRO'),
 (7.673892261526158e-05, 'AirportTo_GTR'),
 (7.645526842384774e-05, 'AirportTo_CSG'),

In [79]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.65      0.67      0.54      0.66      0.60      0.37     89801
          1       0.57      0.54      0.67      0.55      0.60      0.36     72014

avg / total       0.61      0.61      0.60      0.61      0.60      0.36    161815