In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
import plotly.express as px
import os

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
#Indicate columns and target
columns = [
    "id","Airline","Delay","Flight","AirportFrom","AirportTo","DayOfWeek","Length"
]

target = ["Delay"]

In [6]:
file_path = Path("new_airlines")
airlines_df = pd.read_csv(file_path)
airlines_df

            id Airline  Flight AirportFrom AirportTo DayOfWeek  Length  Delay
0            1      CO     269         SFO       IAH  Thursday     205      1
1            2      US    1558         PHX       CLT  Thursday     222      1
2            3      AA    2400         LAX       DFW  Thursday     165      1
3            4      AA    2466         SFO       DFW  Thursday     195      1
4            5      AS     108         ANC       SEA  Thursday     202      0
...        ...     ...     ...         ...       ...       ...     ...    ...
539378  539379      CO     178         OGG       SNA  Saturday     326      0
539379  539380      FL     398         SEA       ATL  Saturday     305      0
539380  539381      FL     609         SFO       MKE  Saturday     255      0
539381  539382      UA      78         HNL       SFO  Saturday     313      1
539382  539383      US    1442         LAX       PHL  Saturday     301      1

[539383 rows x 8 columns]

In [7]:
#Read data into pandas
#data = pd.read_csv("Airlines.csv")

airlines_df = airlines_df.loc[:, columns].copy()
airlines_df

            id Airline  Delay  Flight AirportFrom AirportTo DayOfWeek  Length
0            1      CO      1     269         SFO       IAH  Thursday     205
1            2      US      1    1558         PHX       CLT  Thursday     222
2            3      AA      1    2400         LAX       DFW  Thursday     165
3            4      AA      1    2466         SFO       DFW  Thursday     195
4            5      AS      0     108         ANC       SEA  Thursday     202
...        ...     ...    ...     ...         ...       ...       ...     ...
539378  539379      CO      0     178         OGG       SNA  Saturday     326
539379  539380      FL      0     398         SEA       ATL  Saturday     305
539380  539381      FL      0     609         SFO       MKE  Saturday     255
539381  539382      UA      1      78         HNL       SFO  Saturday     313
539382  539383      US      1    1442         LAX       PHL  Saturday     301

[539383 rows x 8 columns]

In [8]:
#Drop the null columns where all values are null
airlines_df = airlines_df.dropna(axis='columns', how='all')

# Drop the null rows
airlines_df = airlines_df.dropna()
airlines_df

            id Airline  Delay  Flight AirportFrom AirportTo DayOfWeek  Length
0            1      CO      1     269         SFO       IAH  Thursday     205
1            2      US      1    1558         PHX       CLT  Thursday     222
2            3      AA      1    2400         LAX       DFW  Thursday     165
3            4      AA      1    2466         SFO       DFW  Thursday     195
4            5      AS      0     108         ANC       SEA  Thursday     202
...        ...     ...    ...     ...         ...       ...       ...     ...
539378  539379      CO      0     178         OGG       SNA  Saturday     326
539379  539380      FL      0     398         SEA       ATL  Saturday     305
539380  539381      FL      0     609         SFO       MKE  Saturday     255
539381  539382      UA      1      78         HNL       SFO  Saturday     313
539382  539383      US      1    1442         LAX       PHL  Saturday     301

[469504 rows x 8 columns]

In [9]:
#Remove info that does not tell us anything about delay or no delay 
#Flight numbers cannot be used as unique identifier b/c some flights have same flight number but
#are based out of different airports
airlines_df = airlines_df.drop(columns =['id','Flight'],axis=1)
airlines_df

       Airline  Delay AirportFrom AirportTo DayOfWeek  Length
0           CO      1         SFO       IAH  Thursday     205
1           US      1         PHX       CLT  Thursday     222
2           AA      1         LAX       DFW  Thursday     165
3           AA      1         SFO       DFW  Thursday     195
4           AS      0         ANC       SEA  Thursday     202
...        ...    ...         ...       ...       ...     ...
539378      CO      0         OGG       SNA  Saturday     326
539379      FL      0         SEA       ATL  Saturday     305
539380      FL      0         SFO       MKE  Saturday     255
539381      UA      1         HNL       SFO  Saturday     313
539382      US      1         LAX       PHL  Saturday     301

[469504 rows x 6 columns]

# Initial Visulizations/Counts Using Plotly

In [10]:
import pandas as pd
from path import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [11]:
#Create plot grouped by airline to count 
#df = airlines_df[['Airline','Delay']].groupby('Airline').agg('count').reset_index()
#fig = px.bar(airlines_df, x='Airline', y='Delay')
#fig.show()

In [12]:
#Create plot grouped by DayOfWeek to count 
#df = airlines_df[['DayOfWeek','Delay']].groupby('Airline').agg('count').reset_index()
#fig = px.bar(airlines_df, x='DayOfWeek', y='Delay')
#fig.show()

In [13]:

#Create plot grouped by departing airport to count 
#airlines_df = airlines_df[['AirportFrom','Delay']].groupby('AirportFrom').agg('count').reset_index()
#fig = px.bar(airlines_df, x='AirportFrom', y='Delay')
#fig.show()

In [14]:
#Create plot grouped by departing airport to count 
#airlines_df = airlines_df[['AirportTo','Delay']].groupby('AirportTo').agg('count').reset_index()
#fig = px.bar(airlines_df, x='AirportTo', y='Delay')
#fig.show()

In [15]:
#Create plot grouped by departing airport to count 
#airlines_df = data[['Length','Delay']].groupby('Length').agg('count').reset_index()
#fig = px.bar(airlines_df, x='Length', y='Delay')
#fig.show()

# Data Preparation

In [16]:
#Change numbers to day of week to later be converted to 1s and 0s - removed from code because already incorporated in updated CSV
#days = {1:'Monday', 2:'Tuesday', 3:'Wednesday', 4:'Thursday', 5:'Friday', 6:'Saturday', 7:'Sunday'}

In [17]:
#airlines_df['DayOfWeek'] = airlines_df['DayOfWeek'].map(days) - already updated in CSV
airlines_df

       Airline  Delay AirportFrom AirportTo DayOfWeek  Length
0           CO      1         SFO       IAH  Thursday     205
1           US      1         PHX       CLT  Thursday     222
2           AA      1         LAX       DFW  Thursday     165
3           AA      1         SFO       DFW  Thursday     195
4           AS      0         ANC       SEA  Thursday     202
...        ...    ...         ...       ...       ...     ...
539378      CO      0         OGG       SNA  Saturday     326
539379      FL      0         SEA       ATL  Saturday     305
539380      FL      0         SFO       MKE  Saturday     255
539381      UA      1         HNL       SFO  Saturday     313
539382      US      1         LAX       PHL  Saturday     301

[469504 rows x 6 columns]

In [18]:
# Create our features
# Convert string columns to numbers and drop 'delay' column then assign to X
X = pd.get_dummies(airlines_df, columns=['Airline', 'AirportFrom', 'AirportTo', 'DayOfWeek',]).drop('Delay', axis=1)
X

,Length,Airline_9E,Airline_AA,Airline_AS,Airline_B6,Airline_CO,Airline_DL,Airline_EV,Airline_F9,Airline_FL,...,AirportTo_WRG,AirportTo_XNA,AirportTo_YAK,AirportTo_YUM,DayOfWeek_Friday,DayOfWeek_Saturday,DayOfWeek_Sunday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,205,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,222,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,165,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,195,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,202,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539378,326,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
539379,305,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
539380,255,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
539381,313,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
539382,301,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [19]:
X.shape

(469504, 610)

In [20]:
# Create our target
y = airlines_df['Delay']
X.head()

,Length,Airline_9E,Airline_AA,Airline_AS,Airline_B6,Airline_CO,Airline_DL,Airline_EV,Airline_F9,Airline_FL,...,AirportTo_WRG,AirportTo_XNA,AirportTo_YAK,AirportTo_YUM,DayOfWeek_Friday,DayOfWeek_Saturday,DayOfWeek_Sunday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,205,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,222,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,165,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,195,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,202,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [21]:
X.describe()

,Length,Airline_9E,Airline_AA,Airline_AS,Airline_B6,Airline_CO,Airline_DL,Airline_EV,Airline_F9,Airline_FL,...,AirportTo_WRG,AirportTo_XNA,AirportTo_YAK,AirportTo_YUM,DayOfWeek_Friday,DayOfWeek_Saturday,DayOfWeek_Sunday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
count,469504.000000,469504.000000,469504.000000,469504.000000,469504.000000,469504.000000,469504.000000,469504.000000,469504.000000,469504.000000,...,469504.000000,469504.000000,469504.000000,469504.000000,469504.000000,469504.00000,469504.000000,469504.000000,469504.000000,469504.000000
mean,132.114483,0.038360,0.084530,0.021271,0.033429,0.039282,0.112860,0.051868,0.012049,0.038675,...,0.000109,0.002100,0.000104,0.000622,0.194769,0.18157,0.125571,0.191151,0.154991,0.151948
std,70.053219,0.192063,0.278181,0.144288,0.179754,0.194265,0.316421,0.221760,0.109104,0.192819,...,0.010422,0.045779,0.010215,0.024931,0.396023,0.38549,0.331365,0.393208,0.361897,0.358970
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,81.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,115.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
75%,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
max,655.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000

In [22]:
y.value_counts()

0    260933
1    208571
Name: Delay, dtype: int64

In [23]:
## Labels are the values we want to predict
#labels = np.array(X['Delay'])

# Remove the labels from the features
# axis 1 refers to the columns
#X = X.drop('Delay', axis = 1)
# Saving feature names for later use
#X_list = list(X.columns)
# Convert to numpy array
#X = np.array(X)

In [24]:
#d = {}    
# airlines_df = airlines_df.replace(x)

# Split into training and testing splits

In [25]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
from collections import Counter


# Split the data into training and testing sets - used random_state to make the data reproducible and ensure that same rows are assigned to train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [40]:
# Initial imports.
import pandas as pd
from path import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [41]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [42]:
#Check balances
print(Counter(y_train))
print(Counter(y_test))

Counter({0: 195700, 1: 156428})
Counter({0: 65233, 1: 52143})

# Ensemble Learners
## Used to compare which algorithm results in best performance
## Chosen in an effort to improve the accuracy and robustness of the model, decrease variance of the model, and increase overall performance of the model

# Balanced Random Forest Classifier
## Chosen to rank importance of input variables, run efficiently on large datasets, and are robust against overfitting

In [44]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
random_f = RandomForestClassifier(n_estimators = 128)

In [45]:
#Fit the model
random_f = random_f.fit(X_train_scaled, y_train, sample_weight=None)

In [46]:
# Calculated the balanced accuracy score
y_pred = random_f.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5927217829903274

In [47]:
# Display the confusion matrix
# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[59245,  5988],
       [37687, 14456]])

In [48]:
#Create dataframe for the cm 
cm_df = pd.DataFrame(
    cm, index=["Actual Not_Delayed", "Actual Delayed"], columns=["Predicted Not_Delayed", "Predicted Delayed"])
cm_df

                    Predicted Not_Delayed  Predicted Delayed
Actual Not_Delayed                  59245               5988
Actual Delayed                      37687              14456

In [49]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, y_pred)

In [50]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, y_pred))

Confusion Matrix

                    Predicted Not_Delayed  Predicted Delayed
Actual Not_Delayed                  59245               5988
Actual Delayed                      37687              14456

Accuracy Score : 0.627905193565976
Classification Report
              precision    recall  f1-score   support

           0       0.61      0.91      0.73     65233
           1       0.71      0.28      0.40     52143

    accuracy                           0.63    117376
   macro avg       0.66      0.59      0.56    117376
weighted avg       0.65      0.63      0.58    117376

In [51]:
# Calculate feature importance in the Random Forest model.
importances = random_f.feature_importances_
importances

array([4.57237371e-01, 2.05857052e-03, 3.32105637e-03, 1.84486492e-03,
       1.95260248e-03, 4.62759930e-03, 4.13599627e-03, 2.08424164e-03,
       1.18156228e-03, 5.78032836e-03, 8.00382429e-04, 3.77144670e-03,
       4.23653641e-03, 3.26007555e-03, 5.50720184e-03, 4.86182275e-03,
       7.16721459e-02, 2.62517883e-03, 5.25062755e-03, 2.60384741e-04,
       6.72113088e-05, 9.98617186e-04, 4.19638232e-05, 2.05470267e-05,
       1.17421188e-04, 3.63402705e-05, 1.49836794e-05, 3.52001367e-05,
       1.77385298e-04, 1.06185027e-04, 6.96418064e-04, 2.45206628e-04,
       3.71893656e-04, 1.68042476e-04, 2.87768504e-03, 3.35679769e-04,
       1.41882059e-03, 3.25030641e-04, 1.35049997e-04, 1.37285485e-04,
       1.15264990e-03, 6.88538296e-05, 1.31676696e-04, 5.67773718e-05,
       3.64642069e-05, 7.89153266e-04, 2.02008558e-04, 2.13547877e-04,
       3.84440391e-05, 1.58030180e-05, 3.28444781e-04, 1.54813625e-03,
       6.15074061e-04, 2.37402788e-03, 5.78175109e-05, 1.24032627e-04,
       6.99172647e-05, 7.97894448e-05, 4.34862271e-05, 2.35558719e-04,
       4.48663005e-04, 1.04767248e-03, 5.35263207e-04, 2.64527622e-03,
       2.68538372e-04, 3.54430784e-04, 4.83782102e-04, 5.76775096e-05,
       2.88430578e-05, 5.13001634e-05, 1.80417887e-04, 6.16441403e-05,
       5.46074138e-04, 5.10443554e-05, 3.45822906e-04, 4.73064301e-05,
       1.62847948e-03, 2.04266356e-05, 2.38294281e-03, 1.42419004e-03,
       8.89833570e-05, 3.70037792e-05, 9.24299939e-05, 3.75544298e-04,
       3.35276687e-05, 1.15551984e-04, 2.04517892e-04, 4.98068936e-04,
       8.43577886e-05, 1.66934861e-03, 5.22462186e-05, 2.11073747e-05,
       1.43219779e-04, 1.92021908e-03, 8.18621608e-04, 2.13107465e-05,
       1.78684037e-03, 2.36189654e-03, 2.26856072e-03, 8.06541874e-05,
       1.86506584e-04, 8.39145966e-05, 7.35801192e-04, 2.80433527e-03,
       4.47614584e-05, 5.20472304e-04, 2.69162157e-04, 7.21378500e-05,
       7.46765253e-05, 5.76573050e-04, 5.93907133e-05, 1.68751389e-04,
       1.92181094e-04, 5.58654681e-05, 2.04255808e-03, 1.42324968e-04,
       9.92727514e-05, 3.08227224e-04, 3.40327965e-04, 1.35300449e-04,
       1.08785404e-04, 4.72465466e-05, 1.75165338e-03, 4.55640842e-05,
       3.35436333e-04, 3.53723592e-04, 7.81425177e-05, 2.77259239e-04,
       1.23700871e-04, 7.26817594e-04, 8.02124007e-05, 2.03171936e-05,
       1.96009208e-04, 1.23076733e-04, 2.50567876e-04, 2.84964642e-04,
       1.04812180e-04, 7.71323422e-04, 4.78966333e-04, 4.54090080e-04,
       9.50403441e-05, 5.62562444e-05, 8.70122807e-05, 1.95611897e-05,
       1.38113198e-04, 1.05270759e-04, 1.07205233e-03, 1.78614560e-03,
       3.48163192e-04, 3.09904070e-04, 5.33762481e-04, 2.86538523e-05,
       1.66163572e-03, 2.70898230e-03, 4.90722450e-04, 1.03655744e-04,
       1.44591517e-04, 1.69351224e-03, 5.09739527e-05, 2.35767094e-04,
       5.12331854e-05, 5.19661732e-05, 6.84700850e-05, 2.56311588e-04,
       4.23540925e-04, 1.14538060e-03, 1.92323014e-03, 8.50427221e-05,
       3.83859868e-04, 7.40033800e-05, 1.30644124e-04, 2.60903020e-03,
       3.00999472e-03, 2.65773461e-04, 5.15865613e-05, 5.65996670e-04,
       2.71904124e-04, 1.94868373e-03, 3.76441457e-04, 2.82123948e-04,
       7.22846967e-04, 5.73879534e-05, 1.53229272e-04, 7.30082393e-05,
       1.29294530e-04, 7.25720480e-05, 7.66733371e-05, 7.70373049e-05,
       4.20721810e-04, 1.50411023e-04, 1.53555235e-03, 2.84239064e-03,
       3.27253171e-04, 4.45916328e-03, 5.20241902e-05, 1.70914087e-03,
       2.81115557e-04, 2.10219698e-04, 1.33168470e-04, 7.66412475e-05,
       7.44662798e-04, 1.25961059e-03, 1.57060364e-03, 3.91238496e-05,
       1.12541015e-04, 4.01560218e-04, 1.59087664e-04, 2.99883872e-05,
       2.17974382e-04, 4.20842741e-05, 1.59732086e-04, 7.55038416e-05,
       1.86483686e-04, 6.27584219e-04, 1.04958808e-04, 2.44863974e-03,
       1.52121798e-03, 1.68749874e-04, 1.54981364e-04, 6.40277668e-05,
       1.96205960e-03, 6.28667248e-04, 1.03801372e-03, 1.12735125e-03,
       8.31294073e-05, 7.34133357e-04, 5.59025473e-03, 8.36603054e-04,
       8.21020577e-05, 7.97675067e-05, 3.10523007e-05, 9.50956915e-04,
       1.28285199e-03, 3.01103239e-04, 1.97636163e-03, 2.60037945e-03,
       2.23350756e-04, 2.35267345e-05, 6.08366248e-05, 1.71999372e-03,
       5.20966150e-05, 3.36866833e-04, 1.46841057e-04, 6.89280346e-05,
       3.66161621e-05, 4.87848192e-04, 7.45388762e-04, 3.43301789e-04,
       2.61518341e-04, 5.88444705e-05, 1.62429913e-04, 1.58420239e-03,
       7.64409503e-04, 9.91433831e-05, 6.84125129e-04, 2.59449587e-04,
       8.40765448e-04, 4.12161359e-05, 1.48652800e-04, 1.31350242e-03,
       4.39728287e-05, 1.47371908e-03, 1.21554885e-03, 5.18500824e-04,
       2.33433739e-04, 3.40528834e-04, 1.18627148e-04, 3.24798247e-05,
       5.53142503e-05, 9.64188455e-04, 1.92390822e-03, 2.60168438e-03,
       3.02954610e-04, 7.24426133e-05, 2.50148094e-04, 3.54155736e-05,
       1.04264621e-03, 1.72287201e-05, 8.03394639e-04, 2.06902306e-03,
       1.24888764e-03, 7.20610068e-05, 1.31033733e-03, 9.43576598e-05,
       3.61706772e-05, 2.78787014e-04, 1.89420515e-03, 2.58953191e-04,
       4.64773043e-05, 6.20331160e-05, 1.75384244e-04, 8.99944545e-04,
       1.45720354e-05, 2.35264956e-04, 2.67856739e-05, 1.86922538e-03,
       1.75883708e-04, 9.96943908e-04, 8.00164894e-04, 1.85516986e-04,
       6.23795493e-05, 3.60181108e-05, 2.30096190e-05, 6.51630494e-04,
       1.03381562e-05, 7.49597062e-05, 2.24552747e-04, 2.29216632e-05,
       5.27186675e-04, 3.29143978e-05, 9.18332322e-05, 3.09456087e-04,
       4.50487193e-05, 9.11274645e-04, 5.49269933e-06, 5.65582317e-05,
       2.28124854e-05, 9.30105525e-05, 5.00927560e-05, 7.52983083e-06,
       1.87429959e-05, 1.41201916e-04, 1.02732821e-04, 6.20278768e-04,
       2.36529681e-04, 3.58251914e-04, 1.76203001e-04, 3.30000316e-03,
       3.11565993e-04, 1.46242313e-03, 2.16241499e-04, 1.31428344e-04,
       1.54549638e-04, 1.15423660e-03, 3.20384939e-05, 1.41267022e-04,
       6.76790266e-05, 3.74974894e-05, 7.75147635e-04, 1.76014584e-04,
       2.18244783e-04, 5.30175109e-05, 1.61749928e-05, 2.84715289e-04,
       1.64698801e-03, 5.52768108e-04, 2.29493370e-03, 5.20246992e-05,
       1.29698096e-04, 1.29975101e-04, 3.96982683e-05, 6.39644589e-05,
       1.93551702e-04, 4.12779519e-04, 1.05286985e-03, 5.94767716e-04,
       1.85383465e-03, 2.95719766e-04, 3.91522569e-04, 4.09762290e-04,
       3.62722268e-05, 3.51171434e-05, 4.05544853e-05, 2.38379032e-04,
       5.30564654e-05, 6.10609041e-04, 2.66990908e-05, 3.66555856e-04,
       5.58399713e-05, 1.48730348e-03, 4.48461706e-05, 1.86484193e-03,
       1.29038434e-03, 9.60456880e-05, 3.57590488e-05, 9.02888609e-05,
       3.60494134e-04, 3.63963882e-05, 1.17027355e-04, 1.18281482e-04,
       2.91890178e-04, 8.02895545e-05, 1.60233939e-03, 6.75816641e-05,
       3.13753523e-05, 1.35737077e-04, 6.12492829e-04, 8.08261330e-04,
       3.45522510e-05, 1.84541453e-03, 2.75169081e-03, 4.17798656e-03,
       5.71962193e-05, 1.53345546e-04, 8.07028750e-05, 6.17891116e-04,
       2.34252192e-03, 5.49570956e-05, 2.96866781e-04, 2.94042846e-04,
       5.08168515e-05, 8.66696391e-05, 6.65181663e-04, 3.65775885e-05,
       1.75064208e-04, 2.16665309e-04, 6.29709799e-05, 2.10418627e-03,
       1.29261178e-04, 1.08839616e-04, 3.43240680e-04, 4.34900775e-04,
       1.20743229e-04, 1.31612256e-04, 4.26313719e-05, 1.64474799e-03,
       3.09627560e-05, 3.45833359e-04, 3.31587227e-04, 7.07166551e-05,
       2.92512915e-04, 1.35965216e-04, 5.21816307e-04, 1.05813048e-04,
       2.72923560e-05, 1.73596228e-04, 5.64569221e-05, 2.60250528e-04,
       3.66860166e-04, 1.19869185e-04, 8.14251640e-04, 5.06697178e-04,
       4.51792337e-04, 9.69294835e-05, 7.51316890e-05, 1.06011127e-04,
       1.57147511e-05, 1.66465112e-04, 1.25890451e-04, 9.43422844e-04,
       1.04062788e-03, 4.50743457e-04, 1.74250712e-04, 5.17828274e-04,
       3.12308413e-05, 1.59281048e-03, 2.21688511e-03, 4.99857270e-04,
       8.86139806e-05, 1.32149028e-04, 1.61039578e-03, 7.49798469e-05,
       2.27289796e-04, 5.62012083e-05, 7.13093591e-05, 5.18529348e-05,
       2.61389419e-04, 3.97895563e-04, 1.10194038e-03, 2.06521156e-03,
       9.20241468e-05, 2.94049404e-04, 7.31784484e-05, 1.57207162e-04,
       2.60378565e-03, 2.49445859e-03, 2.52953241e-04, 6.48078382e-05,
       5.24461351e-04, 1.80151772e-04, 2.07259106e-03, 3.67551239e-04,
       2.38558279e-04, 7.65408318e-04, 5.13757898e-05, 1.34244897e-04,
       7.12671844e-05, 1.22787882e-04, 7.46983743e-05, 5.27787340e-05,
       5.09602791e-05, 2.38535229e-04, 1.47593335e-04, 1.55950871e-03,
       2.46121323e-03, 3.87343936e-04, 2.08886852e-03, 4.88639620e-05,
       1.75903376e-03, 2.50391996e-04, 1.62563209e-04, 1.40167868e-04,
       6.70750584e-05, 5.32339783e-04, 1.45047653e-03, 1.36089843e-03,
       2.88037223e-05, 8.16115173e-05, 3.55820558e-04, 1.61252925e-04,
       4.52798839e-05, 2.01004054e-04, 3.57734115e-05, 1.44774840e-04,
       9.16465753e-05, 1.66671529e-04, 6.66507867e-04, 1.25452608e-04,
       2.21565028e-03, 1.43789744e-03, 1.49577023e-04, 1.32690204e-04,
       6.06405790e-05, 1.07335403e-03, 4.33775496e-04, 9.30359872e-04,
       1.03221467e-03, 7.31568076e-05, 7.23619326e-04, 3.00129126e-03,
       9.18375302e-04, 6.14604227e-05, 1.00748320e-04, 3.47922304e-05,
       9.47944513e-04, 1.36856662e-03, 2.88710683e-04, 1.86634571e-03,
       2.80505647e-03, 1.80542142e-04, 2.93249955e-05, 4.35850446e-05,
       1.55483198e-03, 3.42903954e-05, 3.70210575e-04, 1.75599004e-04,
       9.38515087e-05, 2.50652212e-05, 4.03383803e-04, 7.01262314e-04,
       4.38674053e-04, 2.57881287e-04, 7.14569540e-05, 1.53140255e-04,
       1.51164195e-03, 8.88397895e-04, 1.51394598e-04, 7.36406028e-04,
       2.02074105e-04, 8.24664400e-04, 4.47494957e-05, 1.34269624e-04,
       1.13852357e-03, 4.73028161e-05, 1.62706384e-03, 1.27900530e-03,
       4.67128335e-04, 2.32325479e-04, 2.89204945e-04, 1.29939889e-04,
       3.83085857e-05, 5.55269258e-05, 8.67097499e-04, 1.82846226e-03,
       2.35773127e-03, 3.49102923e-04, 7.95641999e-05, 1.58021346e-04,
       3.76711330e-05, 9.57626822e-04, 3.33195871e-05, 8.85164735e-04,
       1.80897144e-03, 1.07657332e-03, 4.89497697e-05, 1.12959574e-03,
       8.91126809e-05, 2.44028232e-05, 3.35680599e-04, 1.80481762e-03,
       2.69023143e-04, 5.21534577e-05, 4.98865245e-05, 1.38277947e-04,
       7.27716943e-04, 2.48349132e-05, 2.54590231e-04, 2.47362993e-05,
       1.86326792e-03, 1.74372762e-04, 8.29286057e-04, 7.28195170e-04,
       1.95734191e-04, 5.20557406e-05, 2.87532244e-05, 2.44746887e-05,
       6.27183561e-04, 1.71223272e-05, 5.70902226e-05, 2.32706047e-04,
       2.85495204e-05, 6.00826865e-04, 2.97800836e-05, 1.00113178e-04,
       1.94078032e-02, 1.54128872e-02, 1.33182276e-02, 1.62527048e-02,
       1.67919440e-02, 1.86190792e-02])

In [52]:
# We can sort the features by their importance.
sorted(zip(random_f.feature_importances_, X.columns), reverse=True)

[(0.45723737067498704, 'Length'),
 (0.07167214589933849, 'Airline_WN'),
 (0.019407803229071065, 'DayOfWeek_Friday'),
 (0.018619079163938953, 'DayOfWeek_Wednesday'),
 (0.016791944049454645, 'DayOfWeek_Tuesday'),
 (0.0162527048292347, 'DayOfWeek_Thursday'),
 (0.015412887221083627, 'DayOfWeek_Saturday'),
 (0.0133182275817866, 'DayOfWeek_Sunday'),
 (0.005780328355744227, 'Airline_FL'),
 (0.0055902547290859, 'AirportFrom_ORD'),
 (0.005507201844888948, 'Airline_UA'),
 (0.005250627546514792, 'Airline_YV'),
 (0.00486182275038647, 'Airline_US'),
 (0.0046275992969647215, 'Airline_CO'),
 (0.004459163279586243, 'AirportFrom_MDW'),
 (0.0042365364092031834, 'Airline_OH'),
 (0.004177986558225411, 'AirportTo_DFW'),
 (0.004135996269982753, 'Airline_DL'),
 (0.0037714466996526196, 'Airline_MQ'),
 (0.0033210563666646532, 'Airline_AA'),
 (0.00330000315939908, 'AirportTo_ATL'),
 (0.0032600755477790503, 'Airline_OO'),
 (0.003009994715061303, 'AirportFrom_LAX'),
 (0.0030012912633895668, 'AirportTo_ORD'),
 (0.0028776850434000197, 'AirportFrom_ATL'),
 (0.002842390643974312, 'AirportFrom_MCO'),
 (0.0028050564737726806, 'AirportTo_PHX'),
 (0.0028043352693152986, 'AirportFrom_DTW'),
 (0.002751690808614342, 'AirportTo_DEN'),
 (0.0027089822977759146, 'AirportFrom_IAH'),
 (0.002645276215738687, 'AirportFrom_BWI'),
 (0.002625178825826036, 'Airline_XE'),
 (0.002609030201269106, 'AirportFrom_LAS'),
 (0.0026037856470921992, 'AirportTo_LAS'),
 (0.0026016843839638455, 'AirportFrom_SFO'),
 (0.0026003794466422816, 'AirportFrom_PHX'),
 (0.002494458587806598, 'AirportTo_LAX'),
 (0.002461213226159859, 'AirportTo_MCO'),
 (0.0024486397403331, 'AirportFrom_MSP'),
 (0.0023829428061209568, 'AirportFrom_CLT'),
 (0.002374027880397762, 'AirportFrom_BOS'),
 (0.0023618965384845842, 'AirportFrom_DEN'),
 (0.002357731270334496, 'AirportTo_SFO'),
 (0.0023425219195482385, 'AirportTo_DTW'),
 (0.002294933696889897, 'AirportTo_BOS'),
 (0.0022685607213816187, 'AirportFrom_DFW'),
 (0.00221688511071093, 'AirportTo_IAH'),
 (0.0022156502806982116, 'AirportTo_MSP'),
 (0.002104186268109797, 'AirportTo_EWR'),
 (0.002088868517897712, 'AirportTo_MDW'),
 (0.0020842416409892835, 'Airline_EV'),
 (0.0020725910570527925, 'AirportTo_LGA'),
 (0.0020690230553258747, 'AirportFrom_SLC'),
 (0.0020652115591162337, 'AirportTo_JFK'),
 (0.0020585705167809726, 'Airline_9E'),
 (0.002042558080277718, 'AirportFrom_EWR'),
 (0.001976361631355709, 'AirportFrom_PHL'),
 (0.001962059595831043, 'AirportFrom_OAK'),
 (0.001952602477457645, 'Airline_B6'),
 (0.0019486837268835495, 'AirportFrom_LGA'),
 (0.0019239082170419307, 'AirportFrom_SEA'),
 (0.0019232301421178365, 'AirportFrom_JFK'),
 (0.0019202190822374798, 'AirportFrom_DAL'),
 (0.0018942051454833104, 'AirportFrom_STL'),
 (0.0018692253789706174, 'AirportFrom_TPA'),
 (0.0018663457089580495, 'AirportTo_PHL'),
 (0.001864841931847238, 'AirportTo_CLT'),
 (0.0018632679168300564, 'AirportTo_TPA'),
 (0.0018538346547357348, 'AirportTo_BWI'),
 (0.001845414534024099, 'AirportTo_DCA'),
 (0.0018448649188255123, 'Airline_AS'),
 (0.0018284622625416088, 'AirportTo_SEA'),
 (0.0018089714445841917, 'AirportTo_SLC'),
 (0.0018048176168768899, 'AirportTo_STL'),
 (0.0017868403692646996, 'AirportFrom_DCA'),
 (0.0017861455993637883, 'AirportFrom_HOU'),
 (0.001759033756420731, 'AirportTo_MEM'),
 (0.0017516533768310379, 'AirportFrom_FLL'),
 (0.0017199937224162646, 'AirportFrom_PIT'),
 (0.0017091408694484469, 'AirportFrom_MEM'),
 (0.0016935122421947058, 'AirportFrom_IND'),
 (0.0016693486101657799, 'AirportFrom_CVG'),
 (0.001661635716731523, 'AirportFrom_IAD'),
 (0.001646988009665155, 'AirportTo_BNA'),
 (0.0016447479887098174, 'AirportTo_FLL'),
 (0.0016284794834303356, 'AirportFrom_CLE'),
 (0.0016270638376847623, 'AirportTo_SAN'),
 (0.0016103957781710041, 'AirportTo_IND'),
 (0.001602339387795303, 'AirportTo_CVG'),
 (0.001592810482011637, 'AirportTo_IAD'),
 (0.0015842023889863866, 'AirportFrom_RDU'),
 (0.00157060364428924, 'AirportFrom_MKE'),
 (0.0015595087147581622, 'AirportTo_MCI'),
 (0.0015548319800862845, 'AirportTo_PIT'),
 (0.0015481362531331003, 'AirportFrom_BNA'),
 (0.0015355523465893064, 'AirportFrom_MCI'),
 (0.0015212179753833464, 'AirportFrom_MSY'),
 (0.001511641946084611, 'AirportTo_RDU'),
 (0.0014873034821306784, 'AirportTo_CLE'),
 (0.0014737190781316625, 'AirportFrom_SAN'),
 (0.001462423126895757, 'AirportTo_AUS'),
 (0.0014504765339327138, 'AirportTo_MIA'),
 (0.0014378974418785243, 'AirportTo_MSY'),
 (0.001424190043477188, 'AirportFrom_CMH'),
 (0.0014188205911010057, 'AirportFrom_AUS'),
 (0.0013685666190601398, 'AirportTo_PDX'),
 (0.0013608984277544334, 'AirportTo_MKE'),
 (0.0013135024234864619, 'AirportFrom_RSW'),
 (0.0013103373264433053, 'AirportFrom_SNA'),
 (0.001290384338263534, 'AirportTo_CMH'),
 (0.0012828519924110138, 'AirportFrom_PDX'),
 (0.0012790053004082815, 'AirportTo_SAT'),
 (0.0012596105895208154, 'AirportFrom_MIA'),
 (0.0012488876419626896, 'AirportFrom_SMF'),
 (0.001215548854680687, 'AirportFrom_SAT'),
 (0.0011815622841448868, 'Airline_F9'),
 (0.0011542366013059448, 'AirportTo_BDL'),
 (0.0011526499047939554, 'AirportFrom_BDL'),
 (0.0011453805954814579, 'AirportFrom_JAX'),
 (0.0011385235743837222, 'AirportTo_RSW'),
 (0.0011295957422218165, 'AirportTo_SNA'),
 (0.0011273512480313044, 'AirportFrom_OMA'),
 (0.0011019403808438255, 'AirportTo_JAX'),
 (0.0010765733194538461, 'AirportTo_SMF'),
 (0.0010733540331166992, 'AirportTo_OAK'),
 (0.0010720523274876537, 'AirportFrom_HNL'),
 (0.0010528698519582625, 'AirportTo_BUF'),
 (0.0010476724775732489, 'AirportFrom_BUF'),
 (0.0010426462077688476, 'AirportFrom_SJC'),
 (0.0010406278761629177, 'AirportTo_HOU'),
 (0.0010380137185942682, 'AirportFrom_OKC'),
 (0.0010322146704521277, 'AirportTo_OMA'),
 (0.0009986171864678952, 'AirportFrom_ABQ'),
 (0.0009969439083059274, 'AirportFrom_TUL'),
 (0.0009641884545247151, 'AirportFrom_SDF'),
 (0.0009576268220803222, 'AirportTo_SJC'),
 (0.0009509569152689445, 'AirportFrom_PBI'),
 (0.0009479445134490515, 'AirportTo_PBI'),
 (0.0009434228443051817, 'AirportTo_HNL'),
 (0.0009303598718525264, 'AirportTo_OKC'),
 (0.0009183753021120346, 'AirportTo_ORF'),
 (0.0009112746449167456, 'AirportTo_ABQ'),
 (0.000899944544772192, 'AirportFrom_SYR'),
 (0.0008883978947799358, 'AirportTo_RIC'),
 (0.0008851647349383666, 'AirportTo_SJU'),
 (0.0008670974991230967, 'AirportTo_SDF'),
 (0.0008407654479048284, 'AirportFrom_ROC'),
 (0.000836603054171575, 'AirportFrom_ORF'),
 (0.0008292860566300282, 'AirportTo_TUL'),
 (0.0008246644001082483, 'AirportTo_ROC'),
 (0.0008186216076275175, 'AirportFrom_DAY'),
 (0.000814251639794001, 'AirportTo_GRR'),
 (0.0008082613300462406, 'AirportTo_DAY'),
 (0.0008033946386604538, 'AirportFrom_SJU'),
 (0.0008003824291739491, 'Airline_HA'),
 (0.0008001648936498091, 'AirportFrom_TUS'),
 (0.0007891532660606501, 'AirportFrom_BHM'),
 (0.0007751476354980564, 'AirportTo_BHM'),
 (0.0007713234218591765, 'AirportFrom_GRR'),
 (0.0007654083176316541, 'AirportTo_LIT'),
 (0.000764409502569511, 'AirportFrom_RIC'),
 (0.0007453887617578747, 'AirportFrom_PVD'),
 (0.00074466279794858, 'AirportFrom_MHT'),
 (0.0007364060282799079, 'AirportTo_RNO'),
 (0.0007358011920920444, 'AirportFrom_DSM'),
 (0.0007341333568329232, 'AirportFrom_ONT'),
 (0.0007281951697417735, 'AirportTo_TUS'),
 (0.0007277169430901442, 'AirportTo_SYR'),
 (0.00072681759389829, 'AirportFrom_GEG'),
 (0.0007236193260099793, 'AirportTo_ONT'),
 (0.0007228469665655602, 'AirportFrom_LIT'),
 (0.0007012623136754318, 'AirportTo_PVD'),
 (0.0006964180637399789, 'AirportFrom_ALB'),
 (0.0006841251286539317, 'AirportFrom_RNO'),
 (0.0006665078672083603, 'AirportTo_MSN'),
 (0.0006651816632462689, 'AirportTo_ELP'),
 (0.0006516304941570236, 'AirportFrom_TYS'),
 (0.0006286672481483508, 'AirportFrom_OGG'),
 (0.0006275842193560913, 'AirportFrom_MSN'),
 (0.0006271835608110915, 'AirportTo_TYS'),
 (0.0006202787684229816, 'AirportTo_ALB'),
 (0.0006178911156426489, 'AirportTo_DSM'),
 (0.0006150740606846565, 'AirportFrom_BOI'),
 (0.0006124928287189346, 'AirportTo_DAL'),
 (0.0006106090414511114, 'AirportTo_CHS'),
 (0.0006008268653371708, 'AirportTo_XNA'),
 (0.0005947677157719614, 'AirportTo_BUR'),
 (0.0005765730502094792, 'AirportFrom_ELP'),
 (0.0005659966699842714, 'AirportFrom_LEX'),
 (0.0005527681078149819, 'AirportTo_BOI'),
 (0.0005460741375965286, 'AirportFrom_CHS'),
 (0.0005352632073442134, 'AirportFrom_BUR'),
 (0.000533762480766584, 'AirportFrom_HSV'),
 (0.0005323397828452183, 'AirportTo_MHT'),
 (0.0005271866746820151, 'AirportFrom_XNA'),
 (0.0005244613505302713, 'AirportTo_LEX'),
 (0.0005218163069245646, 'AirportTo_GEG'),
 (0.0005204723044182069, 'AirportFrom_ECP'),
 (0.0005185008238451523, 'AirportFrom_SAV'),
 (0.0005178282735120599, 'AirportTo_HSV'),
 (0.000506697177654319, 'AirportTo_GSO'),
 (0.0004998572695733731, 'AirportTo_ICT'),
 (0.000498068935735095, 'AirportFrom_CRW'),
 (0.000490722449529477, 'AirportFrom_ICT'),
 (0.00048784819169359175, 'AirportFrom_PSP'),
 (0.0004837821023494254, 'AirportFrom_CAK'),
 (0.0004789663333716174, 'AirportFrom_GSO'),
 (0.0004671283354574904, 'AirportTo_SAV'),
 (0.00045409007956401123, 'AirportFrom_GSP'),
 (0.0004517923373848097, 'AirportTo_GSP'),
 (0.0004507434569973464, 'AirportTo_HPN'),
 (0.00044866300538653776, 'AirportFrom_BTV'),
 (0.00043867405325196627, 'AirportTo_PWM'),
 (0.00043490077487320006, 'AirportTo_FAT'),
 (0.00043377549621865293, 'AirportTo_OGG'),
 (0.00042354092532485117, 'AirportFrom_JAN'),
 (0.000420721810135548, 'AirportFrom_MAF'),
 (0.00041277951866541194, 'AirportTo_BTV'),
 (0.00040976228955006013, 'AirportTo_CAK'),
 (0.0004033838032915465, 'AirportTo_PSP'),
 (0.0004015602180189713, 'AirportFrom_MLI'),
 (0.0003978955627265425, 'AirportTo_JAN'),
 (0.00039152256899278805, 'AirportTo_CAE'),
 (0.0003873439362532751, 'AirportTo_MDT'),
 (0.0003838598682422359, 'AirportFrom_KOA'),
 (0.0003764414572810652, 'AirportFrom_LGB'),
 (0.00037554429785882426, 'AirportFrom_COS'),
 (0.00037189365567766574, 'AirportFrom_ANC'),
 (0.0003702105754728497, 'AirportTo_PNS'),
 (0.0003675512394256218, 'AirportTo_LGB'),
 (0.0003668601661758588, 'AirportTo_GRB'),
 (0.0003665558564903843, 'AirportTo_CID'),
 (0.0003604941339787246, 'AirportTo_COS'),
 (0.0003582519136974525, 'AirportTo_ANC'),
 (0.00035582055792905497, 'AirportTo_MLI'),
 (0.00035443078363429713, 'AirportFrom_CAE'),
 (0.0003537235920185633, 'AirportFrom_FSD'),
 (0.000349102922632675, 'AirportTo_SGF'),
 (0.0003481631915188436, 'AirportFrom_HPN'),
 (0.0003458333588744336, 'AirportTo_FNT'),
 (0.0003458229058665611, 'AirportFrom_CID'),
 (0.0003433017892705786, 'AirportFrom_PWM'),
 (0.0003432406797438991, 'AirportTo_FAR'),
 (0.00034052883443157027, 'AirportFrom_SBN'),
 (0.00034032796474689746, 'AirportFrom_FAT'),
 (0.00033686683269900595, 'AirportFrom_PNS'),
 (0.00033568059882250914, 'AirportTo_SRQ'),
 (0.0003356797688254458, 'AirportFrom_ATW'),
 (0.00033543633288483547, 'AirportFrom_FNT'),
 (0.0003315872265322582, 'AirportTo_FSD'),
 (0.00032844478082876856, 'AirportFrom_BMI'),
 (0.00032725317139754796, 'AirportFrom_MDT'),
 (0.0003250306407536712, 'AirportFrom_AVL'),
 (0.00031156599298958225, 'AirportTo_ATW'),
 (0.00030990406997860766, 'AirportFrom_HRL'),
 (0.00030945608724660973, 'AirportTo_ABE'),
 (0.00030822722437261896, 'AirportFrom_FAR'),
 (0.00030295460964546917, 'AirportFrom_SGF'),
 (0.0003011032387805611, 'AirportFrom_PHF'),
 (0.00029686678110021794, 'AirportTo_ECP'),
 (0.0002957197660055747, 'AirportTo_BZN'),
 (0.0002940494038242522, 'AirportTo_KOA'),
 (0.00029404284612589483, 'AirportTo_EGE'),
 (0.0002925129150375939, 'AirportTo_FWA'),
 (0.0002918901777069757, 'AirportTo_CRW'),
 (0.00028920494462248553, 'AirportTo_SBN'),
 (0.00028871068300969705, 'AirportTo_PHF'),
 (0.0002849646416878367, 'AirportFrom_GRB'),
 (0.00028471528870970567, 'AirportTo_BMI'),
 (0.0002821239481722375, 'AirportFrom_LIH'),
 (0.00028111555743639275, 'AirportFrom_MFE'),
 (0.00027878701442233644, 'AirportFrom_SRQ'),
 (0.00027725923925246324, 'AirportFrom_FWA'),
 (0.00027190412448351915, 'AirportFrom_LFT'),
 (0.00026916215707526743, 'AirportFrom_EGE'),
 (0.00026902314275260256, 'AirportTo_STT'),
 (0.0002685383716885532, 'AirportFrom_BZN'),
 (0.0002657734611694641, 'AirportFrom_LBB'),
 (0.0002615183412498559, 'AirportFrom_RAP'),
 (0.0002613894194383399, 'AirportTo_JAC'),
 (0.000260384741300329, 'AirportFrom_ABE'),
 (0.00026025052831858084, 'AirportTo_GPT'),
 (0.00025944958662921144, 'AirportFrom_ROA'),
 (0.00025895319142530467, 'AirportFrom_STT'),
 (0.0002578812867571097, 'AirportTo_RAP'),
 (0.00025631158763548384, 'AirportFrom_JAC'),
 (0.0002545902311971688, 'AirportTo_TLH'),
 (0.0002529532406010152, 'AirportTo_LBB'),
 (0.00025056787570852906, 'AirportFrom_GPT'),
 (0.0002503919962357843, 'AirportTo_MFE'),
 (0.00025014809434855236, 'AirportFrom_SHV'),
 (0.0002452066280744745, 'AirportFrom_AMA'),
 (0.00023855827858625643, 'AirportTo_LIH'),
 (0.00023853522920778318, 'AirportTo_MAF'),
 (0.00023837903176221085, 'AirportTo_CHA'),
 (0.00023652968141276332, 'AirportTo_AMA'),
 (0.00023576709430327462, 'AirportFrom_ISP'),
 (0.00023555871889454667, 'AirportFrom_BTR'),
 (0.00023526495576571037, 'AirportFrom_TLH'),
 (0.00023343373936944505, 'AirportFrom_SBA'),
 (0.0002327060470249553, 'AirportTo_VPS'),
 (0.000232325478693142, 'AirportTo_SBA'),
 (0.00022728979553389984, 'AirportTo_ISP'),
 (0.00022455274746089438, 'AirportFrom_VPS'),
 (0.0002233507555724648, 'AirportFrom_PIA'),
 (0.00021824478349025575, 'AirportTo_BIS'),
 (0.0002179743816342301, 'AirportFrom_MOB'),
 (0.0002166653093820359, 'AirportTo_EVV'),
 (0.00021624149853523023, 'AirportTo_AVL'),
 (0.0002135478768860735, 'AirportFrom_BIS'),
 (0.0002102196983641344, 'AirportFrom_MFR'),
 (0.00020451789231565738, 'AirportFrom_CRP'),
 (0.00020207410483849005, 'AirportTo_ROA'),
 (0.0002020085579357218, 'AirportFrom_BIL'),
 (0.00020100405449989314, 'AirportTo_MOB'),
 (0.00019600920825433617, 'AirportFrom_GJT'),
 (0.00019573419139083624, 'AirportTo_TVC'),
 (0.0001935517024302159, 'AirportTo_BTR'),
 (0.00019218109439910806, 'AirportFrom_EVV'),
 (0.0001865065841666623, 'AirportFrom_DLH'),
 (0.00018648368609127468, 'AirportFrom_MRY'),
 (0.0001855169855300252, 'AirportFrom_TVC'),
 (0.0001805421423719006, 'AirportTo_PIA'),
 (0.00018041788664399994, 'AirportFrom_CHA'),
 (0.00018015177205222294, 'AirportTo_LFT'),
 (0.00017738529823639273, 'AirportFrom_AEX'),
 (0.00017620300062350528, 'AirportTo_ASE'),
 (0.00017601458369131905, 'AirportTo_BIL'),
 (0.0001758837075989392, 'AirportFrom_TRI'),
 (0.00017559900446968279, 'AirportTo_PSC'),
 (0.00017538424422149212, 'AirportFrom_SWF'),
 (0.0001750642075398856, 'AirportTo_EUG'),
 (0.0001743727621390033, 'AirportTo_TRI'),
 (0.0001742507123698073, 'AirportTo_HRL'),
 (0.00017359622787820815, 'AirportTo_GJT'),
 (0.00016875138884042213, 'AirportFrom_EUG'),
 (0.00016874987384076244, 'AirportFrom_MTJ'),
 (0.0001680424758270293, 'AirportFrom_ASE'),
 (0.00016667152854078478, 'AirportTo_MRY'),
 (0.0001664651117160756, 'AirportTo_HDN'),
 (0.0001625632090370107, 'AirportTo_MFR'),
 (0.00016242991305228267, 'AirportFrom_RDM'),
 (0.00016125292493541734, 'AirportTo_MLU'),
 (0.00015973208645869756, 'AirportFrom_MOT'),
 (0.0001590876637162406, 'AirportFrom_MLU'),
 (0.0001580213459573555, 'AirportTo_SHV'),
 (0.00015720716222573084, 'AirportTo_LAN'),
 (0.00015498136406640877, 'AirportFrom_MYR'),
 (0.0001545496383453394, 'AirportTo_AZO'),
 (0.00015334554577409239, 'AirportTo_DLH'),
 (0.00015322927206980276, 'AirportFrom_LNK'),
 (0.0001531402554115836, 'AirportTo_RDM'),
 (0.00015139459750725288, 'AirportTo_RKS'),
 (0.00015041102332369707, 'AirportFrom_MBS'),
 (0.00014957702294200853, 'AirportTo_MTJ'),
 (0.00014865279979635177, 'AirportFrom_RST'),
 (0.00014759333504923037, 'AirportTo_MBS'),
 (0.00014684105661229508, 'AirportFrom_PSC'),
 (0.00014477483993451126, 'AirportTo_MOT'),
 (0.00014459151721392562, 'AirportFrom_ILM'),
 (0.0001432197786536958, 'AirportFrom_DAB'),
 (0.00014232496800195018, 'AirportFrom_EYW'),
 (0.0001412670218970082, 'AirportTo_BFL'),
 (0.00014120191551729403, 'AirportTo_AEX'),
 (0.0001401678682968209, 'AirportTo_MGM'),
 (0.00013827794668742403, 'AirportTo_SWF'),
 (0.00013811319808763973, 'AirportFrom_HDN'),
 (0.00013728548539775103, 'AirportFrom_AZO'),
 (0.0001359652160571171, 'AirportTo_GCC'),
 (0.00013573707710549807, 'AirportTo_DAB'),
 (0.0001353004491557453, 'AirportFrom_FAY'),
 (0.0001350499971199793, 'AirportFrom_AVP'),
 (0.0001342696244704689, 'AirportTo_RST'),
 (0.0001342448973285503, 'AirportTo_LNK'),
 (0.00013316846998107345, 'AirportFrom_MGM'),
 (0.00013269020397802756, 'AirportTo_MYR'),
 (0.00013214902828991766, 'AirportTo_ILM'),
 (0.00013167669551097737, 'AirportFrom_BFL'),
 (0.00013161225614577977, 'AirportTo_FCA'),
 (0.00013142834434909343, 'AirportTo_AVP'),
 (0.00013064412409173728, 'AirportFrom_LAN'),
 (0.000129975101064811, 'AirportTo_BRO'),
 (0.0001299398891022573, 'AirportTo_SBP'),
 (0.00012969809561644407, 'AirportTo_BQN'),
 (0.00012929453013894803, 'AirportFrom_LSE'),
 (0.00012926117758299102, 'AirportTo_EYW'),
 (0.000125890451356918, 'AirportTo_HLN'),
 (0.00012545260849180243, 'AirportTo_MSO'),
 (0.00012403262701963803, 'AirportFrom_BQN'),
 (0.00012370087107116488, 'AirportFrom_GCC'),
 (0.00012307673259757403, 'AirportFrom_GNV'),
 (0.00012278788220978308, 'AirportTo_LSE'),
 (0.00012074322895007783, 'AirportTo_FAY'),
 (0.00011986918455428535, 'AirportTo_GRK'),
 (0.00011862714805252503, 'AirportFrom_SBP'),
 (0.0001182814821793081, 'AirportTo_CRP'),
 (0.0001174211884011893, 'AirportFrom_ACV'),
 (0.00011702735459957986, 'AirportTo_CPR'),
 (0.00011555198359252464, 'AirportFrom_CPR'),
 (0.00011254101493619554, 'AirportFrom_MLB'),
 (0.00010883961575254346, 'AirportTo_FAI'),
 (0.0001087854035961196, 'AirportFrom_FCA'),
 (0.00010618502727573523, 'AirportFrom_AGS'),
 (0.00010601112725169876, 'AirportTo_GUC'),
 (0.00010581304750964113, 'AirportTo_GFK'),
 (0.00010527075867778615, 'AirportFrom_HLN'),
 (0.00010495880790486678, 'AirportFrom_MSO'),
 (0.00010481218024738966, 'AirportFrom_GRK'),
 (0.00010365574378029177, 'AirportFrom_IDA'),
 (0.00010273282079946258, 'AirportTo_AGS'),
 (0.00010074832035008156, 'AirportTo_OTZ'),
 (0.00010011317818171521, 'AirportTo_YUM'),
 (9.927275135703211e-05, 'AirportFrom_FAI'),
 (9.914338309385865e-05, 'AirportFrom_RKS'),
 (9.692948353362826e-05, 'AirportTo_GTF'),
 (9.604568799272297e-05, 'AirportTo_CMI'),
 (9.504034408948122e-05, 'AirportFrom_GTF'),
 (9.435765983355076e-05, 'AirportFrom_SPI'),
 (9.385150865931426e-05, 'AirportTo_PSE'),
 (9.301055248778232e-05, 'AirportTo_ACV'),
 (9.242999385567565e-05, 'AirportFrom_COD'),
 (9.202414682188145e-05, 'AirportTo_JNU'),
 (9.183323221214327e-05, 'AirportFrom_YUM'),
 (9.164657532922211e-05, 'AirportTo_MQT'),
 (9.02888609022915e-05, 'AirportTo_COD'),
 (8.91126808700751e-05, 'AirportTo_SPI'),
 (8.898335701109831e-05, 'AirportFrom_CMI'),
 (8.86139805873132e-05, 'AirportTo_IDA'),
 (8.701228069713939e-05, 'AirportFrom_GUC'),
 (8.666963912194044e-05, 'AirportTo_ELM'),
 (8.504272212359268e-05, 'AirportFrom_JNU'),
 (8.435778859823561e-05, 'AirportFrom_CSG'),
 (8.391459657191297e-05, 'AirportFrom_DRO'),
 (8.31294072843783e-05, 'AirportFrom_OME'),
 (8.210205773460371e-05, 'AirportFrom_OTH'),
 (8.161151727313515e-05, 'AirportTo_MLB'),
 (8.07028749643909e-05, 'AirportTo_DRO'),
 (8.065418739592474e-05, 'AirportFrom_DHN'),
 (8.028955452582995e-05, 'AirportTo_CSG'),
 (8.021240070705702e-05, 'AirportFrom_GFK'),
 (7.97894448184194e-05, 'AirportFrom_BRW'),
 (7.976750671814535e-05, 'AirportFrom_OTZ'),
 (7.956419994743433e-05, 'AirportTo_SGU'),
 (7.814251772009523e-05, 'AirportFrom_FSM'),
 (7.703730490983581e-05, 'AirportFrom_LYH'),
 (7.667333714463036e-05, 'AirportFrom_LWS'),
 (7.66412474934848e-05, 'AirportFrom_MHK'),
 (7.55038415734665e-05, 'AirportFrom_MQT'),
 (7.513168904955038e-05, 'AirportTo_GTR'),
 (7.497984694846415e-05, 'AirportTo_IPL'),
 (7.495970617507745e-05, 'AirportFrom_VLD'),
 (7.469837430287455e-05, 'AirportTo_LWB'),
 (7.467652531881059e-05, 'AirportFrom_ELM'),
 (7.40033799530246e-05, 'AirportFrom_KTN'),
 (7.317844842119485e-05, 'AirportTo_KTN'),

In [38]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.66      0.60      0.62      0.63      0.61      0.37     65233
          1       0.55      0.62      0.60      0.58      0.61      0.37     52143

avg / total       0.61      0.61      0.61      0.61      0.61      0.37    117376